#+TITLE: PHIL 232 New Syllabus Plan
#+DATE: November 27, 2019
#+AUTHOR: Colin McLear

* Week 1 - Scholasticism & Method 
* Week 2 - Descartes, Skepticism, & the Cogito
- First & Second Meditations
* Week 3 - Dualism & Prob of Interaction
- Descartes: Sixth Med; Objections & Replies for M6 (CSM pp. 110-122, 143-150); Principles of Philosophy Part I.47-74 (CSM 175-187). 
- Correspondence with Princess Elisabeth 
* Week 4 - Dualism as ground for Gender Equality
- Poullain de la Barre on Sex Equality and Women’s Education: /On the Equality of the Two Sexes/, Preface (pp. 49-51), I (pp. 52-61), II (p. 73 (¶¶1-3), pp. 79-85, and pp. 95-111); /On the Education of Ladies/, Preface (pp. 140-142) and Conversation 5 (pp. 236-251).
- Astell, /A Serious Proposal to the Ladies/ I, pp. 9-17, 51-62, 69-83, and 102-109; /A Serious Proposal to the Ladies/ II, pp. 119-122, 127-131, 133-140, 144-153, 176-179, 189-193,199-205, and 231-236.
- Optional Commentary: Karen Detlefsen, “Cartesianism and its Feminist Promise and Limits:  The Case of Mary Astell.”

* Week 5 - Materialism
- Galileo, /Assayer/ (excerpt)
- Descartes, The World chs. 6-7; Principles of Philosophy Part I sections 53 & 68-69, Part 2 all selections, Part 4 sections 199-207 (CSM pp. 189-199, 207-212).
- Hobbes
- Boyle, “Of the Excellency and Grounds of the Corpuscular or Mechanical Philosophy” (MP 308–15)
- MAYBE Locke on knowledge of matter?
* Week 6 - Materialism (continued)
- Cavendish
   * PL XXX (on motion) and PL XXXV (on dualism)
   * Observations XXXI (on atomism)
   * PL XXXVII (on perception)
   * Observations XXXV (Of Knowledge and Perception in General)
   * Observations Q.23 (includes overall summary)
   * Grounds ch. 1-10 (overall summary of matter, motion, and perception)
* Week 7 - Catch up
* Week 8 - Review & Mid-Term
* Week 9 - Idealism
- Leibniz's critique of material substance (/New System/)
- Leibniz's idealism (the /Monadology/)

* Week 10 - Spring Break

* Week 11 - Leibniz on Freedom 
* Week  12 - [[file:../notebook/org/LeibnizEvil.org][Leibniz on Evil]] 
* Week 13 - Spinoza's Monism 
- Spinoza's Monism (/Ethics/ Bk I: especially P5, P7, P11, & P14)
  
* Week 14 - Spinoza (cont)
* Week 15 - Finish Spinoza/Begin Hume on Skpeticism
- Hume on the mind (/Enquiry/, §§1-3, 12)
- Hume on causation (/Enquiry/, §§4-7) 
- Hume on personal identity (/Treatise/, I.vi & appendix) 
* Week 16 - Hume on Religion
  
