* Quiz                                                             :noexport:
1. Locke defines a 'quality' as what?
2. Name one primary quality 
3. Name one secondary quality (label them as such)
4. What is a 'corpuscle'?
5. True or false: Mechanism is a metaphysical claim about what kinds of thing
   there are

* Locke on Essence

  - /Essences/: individuate kinds, and explain why members of the kind
    have the features that they do.
    
- Real Essence :: Internal constitution of a substance that (i) objectively
                  determines its other "discoverable qualities" (e.g. its
                  perceptible properties); (ii) determines what kind of
                  thing a thing is
                  
- Nominal Essence :: The property or properties specified by some kind term,
     by which we sort an individual into a particular kind.

     

  1. We sort things in terms of their nominal, rather than real,
     essences.
  2. We cannot sort things in terms of their real essences.
     
** Skepticism about knowledge of real essences
*** Argument 1
#+BEGIN_QUOTE
The frequent Productions of Monsters, in all the Species of animals, and of
changelings, and other strange issues of humane Birth, carry with them
difficulties, not possible to consist with this Hypothesis: Since it is as
impossible, that two Things, partaking exactly of the same real Essence,
should have different Properties, as that two figures partaking of the same
real Essence of a circle, should have different Properties. But were there no
other reason against it, yet the supposition of Essences, that cannot be
known; and the making of them nevertheless to be that, which distinguishes the
Species of Things, is so wholly useless, and unserviceable to any part of our
Knowledge, that that alone were sufficient to make us lay it by; and content
ourselves with such Essences of the Sorts or Species of Things, as come within
the reach of our Knowledge: which, when seriously considered, will be found,
as I have said, to be nothing else, but those abstract complex Ideas, to which
we have annexed distinct general Names. (III.iii.17)
#+END_QUOTE

1. if the real essence of an individual determined its sensible properties, then two individuals with the same real essence should not differ (so much) in their sensible properties
2. “monsters” (offspring that are thought to be of the same real essence as their parents) are occasionally produced in nature
3. $\therefore$ the real essence does not determine sensible properties OR $\therefore$ there
   are only particular real essences (i.e. no particulars "share" the
   same real essence) and no kinds which contain more than one particular
   

*** Argument 2
#+BEGIN_QUOTE
The only imaginable help in this case would be, that, having framed perfect
complex ideas of the properties of things flowing from their different real
essences, we should thereby distinguish them into species. But neither can
this be done. For, being ignorant of the real essence itself, it is impossible
to know all those properties that flow from it, and are so annexed to it, that
any one of them being away, we may certainly conclude that that essence is not
there, and so the thing is not of that species. We can never know what is the
precise number of properties depending on the real essence of gold, any one of
which failing, the real essence of gold, and consequently gold, would not be
there, unless we knew the real essence of gold itself, and by that determined
that species. (III.vi.19)
#+END_QUOTE

1. For any object, a proper subset of its monadic properties (the essential
   properties) explain the instantiation of its other monadic properties (its
   *propria*).
2. We cannot have any epistemic basis for determining which properties are
   essential without a conception of which *kind* of thing we're concerned with.
3. We cannot determine which kind a particular belongs to without a grasp of
   its essence.
4. $\therefore$ We have no basis for determining the essential properties of any object.

   
** Scientific Knowledge of nature
- Corpuscularianism is the best model of what scientific knowledge of
  nature would look like BUT:
  - We can't know for sure that corpuscularianism is true
  - Even if we did know it was true we couldn't have genuinely scientific
    knowledge of nature
    - Obscurity :: we cannot know the real essences of material bodies
                   because we cannot know the properties of their smallest
                   parts (their material constitution)
    - Inscrutability :: even if we did know the real essences of material
                        bodies via their primary qualities, the
                        connections between primary and secondary
                        qualities are inscrutable to us (though maybe not
                        to God, angels, etc.)
                        
* Knowledge
#+BEGIN_QUOTE
  Since the mind, in all its thoughts and reasonings, hath no other
  immediate object but its own ideas, which it alone does or can
  contemplate, it is evident that our knowledge is only conversant about
  them...Knowledge then seems to me to be nothing but the perception of
  the connexion of and agreement, or disagreement and repugnancy of any
  of our ideas. In this alone it consists. (IV.i.1-2)
#+END_QUOTE

1. Knowledge is of /ideas/ and their relations (of agreement or "repugnancy")
   not of things in the world
   a. does this commit Locke to a kind of "veil of perception" skepticism?
2. Knowledge requires the subject's /perception/ of ideas and their relationships
3. When you have knowledge you have certainty
