#+title: Paper Topics

--------------

You are required to write a paper in two drafts. The second draft should
reflect consideration of comments made on the initial version. Papers should
range between 750-2000 words, or roughly, 3-6 double spaced pages. Some latitude is
allowed here, but less than three pages is unlikely to be enough to answer any
of questions raised below. Similarly, you shouldn't need more than six pages
to answer the prompt satisfactorily. Please follow the formatting directions
specified on the syllabus.

I expect papers to be:

1. /Clear/: Write in short and complete sentences. Where possible,
   sacrifice elegance in favor of clarity. Signpost heavily. Avoid
   needless generality.
2. /Arguments/: Your paper should have a thesis for which it argues.
   Autobiographical reportage should be kept to a minimum. Present
   reasons for your position, and present counterarguments where
   relevant.
3. /Appropriately Sourced/: To the extent that you consult secondary
   sources (you are free to do so but not required) you must document
   them in a bibliography. This means any sources you consulted, not
   just what you explicitly quote. I also expect you to make appropriate
   use of the primary sources relevant to your discussion (e.g.
   Descartes's /Meditations/, or Locke's /Essay/). When referring to a
   figure's ideas, cite the relevant area of the text in which this idea
   is expressed or referred to.
   
You can also take a look at the [[file:{filename}/notes/PaperRubric.pdf][rubric]] I used for grading papers.  

I would like to see a *paper proposal*, consisting of (i) a thesis statement;
(ii) a sketch of your argument, sent to me *by email* no later than *Friday,
March 16^th* Please put "phil 232 paper proposal" in the subject line.

- The first draft of the paper is due *via email* on *Friday, April 13^th by 5 pm*. 
- The second and final draft is due *via email* on *Wednesday, May 2^nd* by 5 pm.

--------------

** Paper topics
   :PROPERTIES:
   :CUSTOM_ID: paper-topics
   :END:

1. Descartes's '/cogito/' argument aims at demonstrating at least the
   following two claims: (i) that the Meditator exists; (ii) the nature
   of the Mediator is that of a thinking thing. Is Descartes successful
   here? Why/Why not? You might discuss at least the 'Lichtenburg'
   objection, and the 'Substance Theory' proposal as outlined in the
   class notes.
2. Descartes and Locke take opposing positions as to whether we can have
   scientific knowledge (demonstrative knowledge that is explanatory,
   systematic and secure) of the natural world. Explain their opposing
   positions. Are there reasons to favor one figure over the other?
3. Explain Locke's criticisms of innate ideas and discuss the various
   replies to these criticisms by Leibniz. Are Leibniz's replies
   convincing, and if so why?
4. Leibniz is highly critical of the prevailing theory of matter of his
   time. Explain his critical arguments. Are they convincing? If not
   then explain why. If they are, explain why, and discuss the structure
   of his idealist theory in the /Monadology/. Is his positive position
   convincing?
5. Hume presents a trenchant critique of the scholastic conception of
   causation and necessary connection. Explain his critique. What is
   Hume's positive position on causation? What problems, if any, are there
   with Hume's positive position?
6. Hume presents a critique of prevailing conceptions of personal
   identity. What is this critique? What is Hume's positive conception?
   What problems are there for this conception?
