#+TITLE: In-Class Notes
#+OPTIONS: num:nil

* Week 2 (1/15)
** Quiz
1. What are the four rules in Descartes's "method" for acquiring
   knowledge? 
2. What is epistemic foundationalism?
3. (T/F) Descartes's method of doubt requires that we believe all of our beliefs
   are false 
4. Why does Descartes employ his method of doubt?
5. Name one of the stages of doubt

** Scholastic Background
- Cosmology
- Causal structure of nature (4 causes)
- Hylomorphism
- Aristotelian empiricism 
- Demonstrative science (is it possible?)

** Descartes
- Rene Descartes (1596-1650); /Discourse on the Method/ (1637) & The /Meditations/ (1641)

*** The Method

Descartes puts his method this way:

#+BEGIN_QUOTE
The first was never to accept anything as true if I did not have evident
  knowledge of its truth: that is, carefully to avoid precipitate conclusions
  and preconceptions, and to include nothing more in my judgements than what
  presented itself to my mind so clearly and so distinctly that I had no
  occasion to doubt it. 

  The second, to divide each of the difficulties I examined into as many parts
  as possible and as may be required in order to resolve them better.

  The third, to direct my thoughts in an orderly manner, by beginning with the
  simplest and most easily known objects in order to ascend little by little,
  step by step, to knowledge of the most complex, and by supposing some order
  even among objects that have no natural order of precedence.

  And the last, throughout to make enumerations so complete, and reviews so
  comprehensive, that I could be sure of leaving nothing out. (AT VI:18-19)
#+END_QUOTE

We can put the method more concisely as follows:

1. Accept as true only that for which one has proper evidence—viz., clear
   and distinct ideas;
2. Resolve problems into their simplest parts
3. Move from the simple and known to the complex 
4. Thoroughly review and check one’s work to be sure it is comprehensive and complete
 
*** The Meditations

- Meditation as literary form
- Tree metaphor for all human knowledge:
  "The roots are metaphysics, the trunk is physics, and the branches
  emerging from the trunk are all the other sciences, which may be
  reduced to three principal ones, namely medicine, mechanics and
  morals” (AT IXB 14: CSM I 186)


** Meditation 1
***** Structure of Med 1
- The project (7:17-18)
  - Foundationalism :: conception of knowledge as starting from
    absolutely certain first principles, typically known without
    inference from anything else (e.g. they are "self-evident")

  - Method of doubt
    - Suspend judgment concerning all which is uncertain (i.e. all for
      which one can raise some doubt)
  - In particular, doubt /empiricism/
    - Three "stages of doubt" concerning empiricism
      - stage 1: the senses occasionally deceive 
      - stage 2: the dream argument
      - stage 3: the evil demon
- Against Empiricism
  1. Sensory foundations (7:18)
  2. Sensory fallibility (7:18-19)
  3. Objection: Optimal circumstances (7:19)
  4. Objection: Insanity (7:18-19)
  5. The dream argument (7:19)
  6. Objection: The painter’s analogy (7:19-20)
  7. Deceitful God; Dubitability of mathematics (7:21)
  8. The corrective role of doubt (7:22)
  9. The evil demon (7:22-3)

** Meditation 2
*** Structure of Med 2
-   The review of doubt; the *Cogito* (7:24-5)
-   The nature of the 'I' as thinking thing (7:25-7)
-   The mind's unknown relation to body (7:27)
-   The mind itself is not 'imageable' (7:27-8)
-   The variety and unity of thought (7:28-9)
-   The 'Wax Argument' --- our knowledge of body (7:29-33)
-   Analysis of the nature and content of perceptual judgment (7:32)
-   The Mind is better known than (any) body (7:33-4)


*** The Cogito Argument

#+BEGIN_QUOTE
I have convinced myself that there is absolutely nothing in the world, no sky,
no earth, no minds, no bodies. Does it now follow that I too do not exist? No:
if I convinced myself of something then I certainly existed. But there is a
deceiver of supreme power and cunning who is deliberately and constantly
deceiving me. In that case I too undoubtedly exist, if he is deceiving me; and
let him deceive me as much as he can, he will never bring it about that I am
nothing so long as I think that I am something. So after considering
everything very thoroughly, I must finally conclude that this proposition, /I
am, I exist/, is necessarily true whenever it is put forward by me or conceived
in my mind. (7:25)
#+END_QUOTE

**** Problems

- Begs question 
  - 'I' premise assumes existence of subject

- Reformulated argument
  1. A thing is composed of its properties or characteristics /plus/ an
     underlying substance to which they belong
  2. If there is a property or characteristic, then there must be a
     substance to which it belongs.
  3. A thought is a property.
  4. If there is a thought, then there is a substance to which it belongs.
  5. There is a thought.
  6. \therefore There is a substance to which this thought belongs: "I".
* Week 3 (1/22)
- There is no seems/is distinction with respect to certain classes of thought
- How can we be certain that we have the nature that the Meditator claims
  that we have (as thinking substance)? -- Maybe we are just thoughts of the
  "world soul"? 

** Objections (review)
- Begging the question
  - Remove problem by introducing premises?
    1. There is thinking 
    2. For any instantiated property there is a thing---a
       "substance"---that has that property
    3. So there is a thinking thing (1,2)
    4. So I am thinking 
- Invalid argument
  - Can't move from impersonal premises to 1st person conclusion


** A defense
Lichtenberg's objection: "there is no subject of thought -- D's starting
point should be: 'there is thought"

- (T1) It is thought: P
- (T2) It is thought: Q

But then we can't infer from T1 & T2 that

- (T3) It is thought: P & Q

From Lichtenberg's starting point we can't explain the "unity" of thought
-- perhaps this justifies the starting point of Descartes's /Cogito/
argument?

** The Wax Argument

Aims to show two things:
1. the nature of body is known via intellect not senses (7:30-1)
2. the nature of mind is better known than body (7:33)
  
  
*** The Argument
1. I can grasp that this melted wax is flexible and changeable so as to
   be capable of innumerable changes of shape.
2. Imagination could allow me to grasp this fact only by representing
   these changes by an image of each possible shape.
3. My imagination cannot represent the innumerable shapes required.
4. So it is not the imagination that allows me to grasp this capability of
   the wax.
5. But I do grasp this capability, so it must be by a faculty other
   than (sense or) imagination: call it the "intellect".
   

** Quiz
1. What is the "cogito" argument? 
   - "I think, I exist" is true whenever I think it
2. Name one way in which the argument is problematic
   - begs the question 
   - invalid 
3. What does Descartes assume is entailed by the existence of a thought?
   - a thinker (i.e. a substance that has the property of thinking)
4. T/F: The Meditator claims that it can be certain that it is a "thinking
   thing"?
   - T 
5. T/F: The wax argument shows that body is known via the senses only 
   - F
     
** The nature of the subject as a thinking thing
Descartes further understands the 'I' in terms of the kinds of activity
it can undertake. A thinking thing is "a thing that doubts, understands,
affirms, denies, is willing, is unwilling, and also imagines and has
sensory perceptions” (7:28). 

What makes all these characteristic activities go together? 
  - one and same being is *conscious* of engaging in all these kinds of activity

    1. What makes a "mind" a mind?
    2. What are the identity conditions under which a particular mind persists?
** Results of the Cogito
- The results of the Cogito inquiry
  - I am certain that:
    - I exist
    - I exist as a thinking thing
    - A thinking thing is a thing that doubts, understands, affirms, denies, is
      willing or unwilling, imagines, and has sensory perceptions
    - The intellect is an essential feature of a mind, and of all mental
      activities
** Three possible uses of the cogito
1. the 'foundationalist' answer: what is certain is a 'first principle' from
   which we derive other knowledge;
2. the 'systematicity' answer: what is certain is systematically connected with
   other knowledge (e.g. knowledge that 2 + 2 = 4 might be systematically
   related to knowledge that 1 + 1 + 2 = 4, etc.);
3. the 'methodological' answer: what is certain reveal a method for deriving
   other certainties.

** Meditation 3

1. I know with certainty that I am a thinking thing.
2. This knowledge is based solely on a clear and distinct perception of
   its truth. 
3. Clear and distinct perception would not be sufficient to yield such
   knowledge if it were in any way fallible.
4. \therefore Clear and distinct perception provides a sufficient
   ground for knowledge; whatever I so perceive is true.


- Truth Rule :: Whenever I C&D perceive then what I perceive is true & I can be
                certain of it /as such/ 

- *Problem*: could a deceitful god make me go astray even when I have C&D ideas?
* Week 4 (1/29)
** Meditation 3
1. I know with certainty that I am a thinking thing.
2. This knowledge is based solely on a clear and distinct perception of
   its truth. 
3. Clear and distinct perception would not be sufficient to yield such
   knowledge if it were in any way fallible.
4. \therefore Clear and distinct perception provides a sufficient
   ground for knowledge; whatever I so perceive is true.

   

- Truth Rule :: whatever I perceive very clearly and distinctly is true
- *Problem*: could a deceitful god make me go astray even when I have C&D ideas?
  - Reply: We have to (1) examine what ideas are and (2) prove that God exists
    and is no deceiver

*** Ideas
- What are ideas?
  - Mental "representations" :: entities by means of which one is aware of
       things outside or independent of one's mind 

- Two senses of "reality" of idea
  - objective reality :: what the idea is an idea /of/ -- the "content" of
       the idea
  - formal reality :: feature or "mode" of the mind


*** Sources of Ideas
- Where do our ideas (i.e. their content or objective reality) come from?
- Three sources
  1. Adventitious 
  2. Invented/imagined 
  3. Innate 


**** Innate ideas
- What are innate ideas?
  1. An idea one has simply in virtue of having a mind  
  2. An idea gained via reflection on or consciousness of one's nature 
- What, if any, kinds of dependence relations exist between the various
  classes of ideas?


*** Modes of reality
- "Existence" is not "reality"
  - existence appeals to causality/causal effect 
  - reality appeals to power of cause
- Reality as "graded"
  1. Infinite substance   
  2. Finite substance 
  3. Modes (of substance) -- i.e. properties 
*** The Causal Principle
- The causal principle :: there must be at least as much reality in the
     efficient and total cause as in the effect of that cause 
*** Rationalism & the PSR
- Question : why can't something come from nothing?
- Rationalist assumption :: the principles governing the structure
     of nature mirror or are identical with the principles governing
     the structure of our ideas
- The Principle of Sufficient Reason :: For every truth or fact there is a
     sufficient reason

*** The Causal argument
1. The objective reality of an idea must have a cause equal to it or greater
2. The objective reality of my idea of God is that of an omni-omni-omni substance
3. No finite being has sufficient reality to cause the content of my idea of God
4. \therefore The cause of the objective reality of the idea must be God

*** Objections
1. Do we really have such an idea of God?
  - We must because of the "priority of the infinite"

2. Does the idea of God really require an *infinite* cause?
  - No concept of an infinite being could be constructed from finite
    (e.g. sensory) materials

*** Argument for God's existence based on the preservation of finite substance
- /Question/: could I (the meditator) have existed if no "more perfect" being
  existed (7:48) ?
- Four possible sources of my existence:
  1. self-causation
  2. parents
  3. some other finite being
  4. God
- Against (1): only an infinite power could create something from nothing

- Preservation principle :: There is no distinction between preservation
     of existence and creation


1. Any entity that exists exists at discrete moments that are independent of each other
2. The existence of a substance at one moment does not give it the power to
   exist at any other subsequent moment
3. Existence at a moment requires an act equivalent to creation (preservation = creation)
4. No finite entity can create itself
5. ∴ no finite entity can preserve itself from one moment to the next
6. ∴ there must be some entity capable of creation & preservation


** Meditation 4
- God is no deceiver and all-powerful, so why is it that we are created
  with the capacity for error? How is this compatible with the existence
  of a God so conceived?

#+BEGIN_QUOTE
when I concentrate on the nature of God, it seems impossible that he should have
placed in me a faculty which is not perfect of its kind, or which lacks some
perfection which it ought to have...There is, moreover, no doubt that God could
have given me a nature such that I was never mistaken; again, there is no doubt
that he always wills what is best. Is it then better that I should make mistakes
than that I should not do so? (7:55)
#+END_QUOTE

* Week 5 (2/5)
** Quiz
1. Name one source of our ideas that Descartes discusses
   - senses, observation, experience, "adventitious"
   - invented or imagined ideas
   - innate
2. T/F: Descartes needs to prove that God exists to be certain that the
   "cogito" argument is true
   - F
3. T/F: The truth rule states that whenever one thinks, what one thinks is true
   - F
4. T/F: The Med 2 wax argument presupposes that bodies exist
   - F
5. What is the formal reality of an idea?
   - formal reality :: the way an idea exists -- as a mode or property of
                       the mind
   - objective reality :: what the idea is about or represents -- its "content"


** Med 4 - The theory of error

#+BEGIN_QUOTE
I perceive that the power of willing which I received from God is not, when
considered in itself, the cause of my mistakes for it is both extremely ample
and also perfect of its kind. Nor is my power of understanding to blame for
since my understanding comes from God, everything that I understand I
undoubtedly understand correctly, and any error here is impossible. So what then
is the source of my mistakes? It must be simply this: the scope of the will is
wider than that of the intellect; but instead of restricting it within the same
limits, I extend its use to matters which I do not understand. Since the will is
indifferent in such cases, it easily turns aside from what is true and good, and
this is the source of my error and sin. (7:58)
#+END_QUOTE

- The source of error is willing to believe something that is false, or
  for which one lacks sufficient evidence
- We choose or "will" to believe or deny the judgments or ideas presented
  by the understanding  

*** Error as evil -- three responses
1. Maybe we can't always understand God's actions (7:55)
2. Imperfections/evils should be understood at the level of all of creation, not locally
3. In our case, error is the function of a relationship between our faculties


*** Three kinds of causal influence
1. Interactionism
2. Occasionalism
   - direct causal intervention
   - indirect causal intervention via laws of nature
3. Parallelism (divine harmony)
   
   
** Med 5 - Essence & Ontological Argument
1.  Essence of matter is extension (7:63, 71)
2.  Innate ideas of essences (7:63–5)
3.  Ontological argument (7:65–8)


*** Essence of matter
The essence of matter is "continuous quantity" or extension
#+BEGIN_QUOTE
Quantity, for example, or 'continuous' quantity as the philosophers commonly
call it, is something I distinctly imagine. That is, I distinctly imagine the
extension of the quantity (or rather of the thing which is quantified) in
length, breadth and depth. I also enumerate various parts of the thing, and to
these parts I assign various sizes, shapes, positions and local motions; and to
the motions I assign various durations. (7:63)
#+END_QUOTE

*** Extension as "Primary Attribute"
- Primary attribute as essential property of a substance

- essential property :: (i) necessary property of a thing that (ii)
     makes it the kind of thing that it is and (iii) explains other
     properties that a thing may have  

  
1. Intellectual/intelligible claim :: idea of quantity entails other
     ideas (extension entails & is entailed by shape, size, etc)
2. Metaphysical claim : reality is such that if there is extension then
   there is a metaphysical dependence of size, shape, etc., on it 
     



*** The ontological argument
1. Whatever I C+D perceive to belong to the essence of a thing does
2. I C+D perceive that the essence of God includes every perfection
3. It is more perfect to exist than not to existence (existence is a perfection)
4. \therefore Existence is necessarily part of God's essence
5. \therefore God necessarily exists


*** Objections
1. We don't have a C+D perception of God's essence, which means we don't
   have a C+D perception of whether that essence includes existence 
2. Why think that existence is a perfection?
   - maybe "exist" doesn't pick out a property in anything like the way
     "hot" or "good" does -- "existence" isn't a "real predicate" 
   
     
* Week 6 (2/12)
** Quiz
1. In Med 3 Descartes articulates 2 proofs of the existence of God. Name one.
   - casual argument from idea of God
   - preservation/creation of finite beings
2. In his first proof of God’s existence D uses a metaphysical principle. Name
   the principle & briefly describe its content
   - Causal principle
3. T/F: Descartes explains the existence of error as arising because of the
   relation between the imagination and the understanding
   - F
4. T/F: Descartes thinks that finite substances lack the power to persist
   through time on their own 
   - T
5. T/F: Descartes thinks that the power to preserve is the same the as the power
   to create
   - T

** The "Cartesian Circle"
1. I can be certain of P only if I am certain that Q
2. I can be certain of Q only if I am certain that P

P: whatever I perceive clearly and distinctly is true
Q: God exists and is not a deceiver

How does Descartes avoid the circular reasoning? Can he deny either or
both of (1) or (2)?
** Descartes's Memory Response
- We don't need proof of God's existence and non-deceitful nature to certify
  C&D perception, rather only need proof of God to show that we can rely on
  memory of C&D perception
- Worry: doesn't really answer the fundamental objection that we need some
  certification for C&D perception /itself/.
** Alternative Strategies for resolving the Circle
*** 1. Mere psychological certainty not truth
- Maybe Descartes is just after unshakable psychological certainty or
  conviction rather than truth
- Unsatisfying as a general explanation of what Descartes is doing in
  the Meditations (e.g. unsatisfying as explanation of Med 5 argument
  concerning our intellectual grasp of essences)
*** 2. Remove the doubt
Descartes isn't trying to prove that C&D perception is /true/, only that
we have no defensible grounds for doubting C&D perception 

- Maybe not going to work since even just removing doubt about decietful
  god via appeal to our idea of God will rely on C&D perception of the
  content of our idea of God
- Doesn't seem to remove grounds for doubting a "defective origins"
  style objection as from Med 1 (7:21)
  
**** Two Validation Projects
***** Strong Validation of the Intellect
The intellect is capable of discovering and knowing/justifying
metaphysical principles concerning reality
***** Weak Validation of the Intellect 
There are no good grounds for doubting the deliverances of the
intellect -- it is a (generally) reliable faculty for knowledge 
*** 3. Presumption in favor of the intellect
Why couldn't the Meditator reasonably begin with the presumption of the
reliability of the human intellect?

- Worry: begs the question against those who doubt the power/reliability
  of intellect
- Worry: doesn't account for how we can have knowledge of essences of
  real objects (e.g. knowledge of essence of matter or God)


** Is the Circle  Inescapable?
- If D is after a "strong validation" of the intellect then he may be
  unable to escape the circle since he would need positive proof that the
  method of C&D perception is reliable but his only such positive proofs
  (e.g. God's existence) rely on that very method


** Is Descartes's Problem our Problem?
- "Problem of the criterion" :: whether or not we need to know the epistemic principles which justify our claims to knowledge prior to (and perhaps independently of) any knowledge that we have, including knowledge that might be necessary for formulating the principles.
  

  
  
** Meditation 6

*** Three kinds of distinctness
1. conceptual
- distinction necessary for the intelligibility of something 
2. modal
- distinction between properties or modes, but not between things 
3. real 
- distinction between existing things (applies only to substance) --
  specifically that they /could/ exist independent of one another (whether
  they actually do or not). 

  
*** The real distinction argument
**** Three claims
- Complete Being_T :: a thinking thing can exist as a substance whose sole
     essence is thought.
- Complete Being_B :: body can exist as a substance whose sole essence is extension.
- Mutual Exclusion :: mental substance has no bodily modes, and bodily substance has no mental modes.
     
***** God's power
Part [A] says:

#+BEGIN_QUOTE
  [A] I know that everything which I clearly and distinctly understand
  is capable of being created by God so as to correspond exactly with my
  understanding of it. Hence the fact that I can clearly and distinctly
  understand one thing apart from another is enough to make me certain
  that the two things are distinct, since they are capable of being
  separated, at least by God. The question of what kind of power is
  required to bring about such a separation does not affect the
  judgement that the two things are distinct.
#+END_QUOTE

Here is what part A [[http://plato.stanford.edu/entries/descartes-modal/#ReaDis][seems to be arguing]]:

1. I clearly and distinctly understand mind apart from body and body
   apart from mind.
2. God can bring about whatever I clearly and distinctly perceive.
3. God can bring about that mind is apart from body and body is apart
   from mind.
4. If God can bring about that mind is apart from body and body is apart
   from mind, then mind and body can exist apart.
5. \therefore Mind and body can exist apart.
   
   - How do we know that we are C&D perceiving mind apart from body,
     etc.? 

   - What we would want is a *natural* distinction between mind &
     body, not a *supernatural* or *miraculous* distinction
     

***** Knowing one's essence
#+BEGIN_QUOTE
  [B] Thus, simply by knowing that I exist and seeing at the same time
  that absolutely nothing else belongs to my nature or essence except
  that I am a thinking thing, I can infer correctly that my essence
  consists solely in the fact that I am a thinking thing. 
#+END_QUOTE

1. One's self exists
2. Nothing belongs to one’s essence or nature other than thinking
3. ∴ All properties of oneself have to be conceived via this essence – thought

Is this argument enough to yield the Real Distinction? Presumably not – it just tells us that our essence is that of a thinking being, it doesn’t tell us that all thinking beings are independent of any body. It doesn’t give us Mutual Exclusion. But it does give us Complete Being-T.

***** Real distinctness
#+BEGIN_QUOTE
  [C] It is true that I may have (or, to anticipate, that I certainly have) a
  body that is very closely joined to me. But nevertheless, on the one hand I
  have a clear and distinct idea of myself, in so far as I am simply a
  thinking, non-extended thing; and on the other hand I have a distinct idea
  of body, in so far as this is simply an extended, non-thinking thing. And
  accordingly, it is certain that I am really distinct from my body, and can
  exist without it.
#+END_QUOTE

According to the Meditator's distinct and clear ideas:

1. The self is a thinking and non-extended thing
2. Corporeal substance is extended and non-thinking

This gives us /Mutual Exclusion/. If we assume Complete Being_B then it seems D gives us what we need to conclude that mind and body are Really Distinct

- Is it clear that if a thing can exist that has no bodily properties then that thing can exist apart from bodies?
  - could there be some other kind of dependence relation between minds and bodies apart from modal/property dependence?
    - not, presumably, if we are talking about substances, since substances are independent beings

***** Objections 
- How do we know that the apparent distinctness of mind and body is not due to our ignorance of their real identity?

#+BEGIN_QUOTE
  Suppose someone knows for certain that the angle in a semi-circle is a
  right angle, and hence that the triangle formed by this angle and the
  diameter of the circle is right-angled. In spite of this, he may
  doubt, or not yet have grasped for certain, that the square on the
  hypotenuse is equal to the squares on the other two sides; indeed he
  may even deny this if he is misled by some fallacy. But now, if he
  uses the same argument as that proposed by our illustrious author, he
  may appear to have confirmation of his false belief, as follows: 'I
  clearly and distinctly perceive', he may say, 'that the triangle is
  right-angled; but I doubt that the square on the hypotenuse is equal
  to the squares on the other two sides; therefore it does not belong to
  the essence of the triangle that the square on its hypotenuse is equal
  to the squares on the other sides.' (7:201-2)
#+END_QUOTE

Descartes’s answer, perhaps unsurprisingly, refers to what the Meditator has learned so far

- (i) the fact that the Meditator has clear and distinct ideas of mind and body, where each excludes the features of other
- (ii) the nature of clear and distinct ideas is such that they adequately represent how reality is (or what is really possible).

So Descartes simply denies Arnauld’s premise, that the subject has a clear and distinct idea of a right triangle. If they really did have such an idea, Descartes argues, they would know that the Pythagorean theorem is true of such triangles.

To reject Descartes’s argument we must reject either

- (i) the claim that we (or the Meditator) have clear and distinct ideas of the mind as distinct from the body, or
- (ii) that clear and distinct perception is a reliable guide to real possibility/actuality.
  
***** Causation:

The dualist position articulated here raises problems for D - how do minds and bodies interact, if at all?

- Interactionism
- Occasionalism
- Parallelism


* Week 7 (2/19)
*** The real distinction argument
**** Three claims
- Complete Being_T :: a thinking thing can exist as a substance whose sole
     essence is thought.
- Complete Being_B :: body can exist as a substance whose sole essence is extension.
- Mutual Exclusion :: mental substance has no bodily modes, and bodily substance has no mental modes.
     
***** God's power
Part [A] says:

#+BEGIN_QUOTE
  [A] I know that everything which I clearly and distinctly understand
  is capable of being created by God so as to correspond exactly with my
  understanding of it. Hence the fact that I can clearly and distinctly
  understand one thing apart from another is enough to make me certain
  that the two things are distinct, since they are capable of being
  separated, at least by God. The question of what kind of power is
  required to bring about such a separation does not affect the
  judgement that the two things are distinct.
#+END_QUOTE

Here is what part A [[http://plato.stanford.edu/entries/descartes-modal/#ReaDis][seems to be arguing]]:

1. I clearly and distinctly understand mind apart from body and body
   apart from mind.
2. God can bring about whatever I clearly and distinctly perceive.
3. God can bring about that mind is apart from body and body is apart
   from mind.
4. If God can bring about that mind is apart from body and body is apart
   from mind, then mind and body can exist apart.
5. \therefore Mind and body can exist apart.
   
- We want to know whether mind and body naturally exist apart, not whether God can miraculously separate them…

***** Knowing one's essence
#+BEGIN_QUOTE
  [B] Thus, simply by knowing that I exist and seeing at the same time
  that absolutely nothing else belongs to my nature or essence except
  that I am a thinking thing, I can infer correctly that my essence
  consists solely in the fact that I am a thinking thing. 
#+END_QUOTE

1. One's self exists
2. Nothing belongs to one’s essence or nature other than thinking
3. ∴ All properties of oneself have to be conceived via this essence – thought

Is this argument enough to yield the Real Distinction? Presumably not – it just tells us that our essence is that of a thinking being, it doesn’t tell us that all thinking beings are independent of any body. It doesn’t give us Mutual Exclusion. But it does give us Complete Being-T.

***** Real distinctness
#+BEGIN_QUOTE
  [C] It is true that I may have (or, to anticipate, that I certainly have) a
  body that is very closely joined to me. But nevertheless, on the one hand I
  have a clear and distinct idea of myself, in so far as I am simply a
  thinking, non-extended thing; and on the other hand I have a distinct idea
  of body, in so far as this is simply an extended, non-thinking thing. And
  accordingly, it is certain that I am really distinct from my body, and can
  exist without it.
#+END_QUOTE

According to the Meditator's distinct and clear ideas:

1. The self is a thinking and non-extended thing
2. Corporeal substance is extended and non-thinking

This gives us /Mutual Exclusion/. If we assume Complete Being_B then it seems D gives us what we need to conclude that mind and body are Really Distinct

- Is it clear that if a thing can exist that has no bodily properties then that thing can exist apart from bodies?
  - could there be some other kind of dependence relation between minds and bodies apart from modal/property dependence?
    - not, presumably, if we are talking about substances, since substances are independent beings

***** Objections 
- How do we know that the apparent distinctness of mind and body is not due to our ignorance of their real identity?

#+BEGIN_QUOTE
  Suppose someone knows for certain that the angle in a semi-circle is a
  right angle, and hence that the triangle formed by this angle and the
  diameter of the circle is right-angled. In spite of this, he may
  doubt, or not yet have grasped for certain, that the square on the
  hypotenuse is equal to the squares on the other two sides; indeed he
  may even deny this if he is misled by some fallacy. But now, if he
  uses the same argument as that proposed by our illustrious author, he
  may appear to have confirmation of his false belief, as follows: 'I
  clearly and distinctly perceive', he may say, 'that the triangle is
  right-angled; but I doubt that the square on the hypotenuse is equal
  to the squares on the other two sides; therefore it does not belong to
  the essence of the triangle that the square on its hypotenuse is equal
  to the squares on the other sides.' (7:201-2)
#+END_QUOTE

Descartes’s answer, perhaps unsurprisingly, refers to what the Meditator has learned so far

- (i) the fact that the Meditator has clear and distinct ideas of mind and body, where each excludes the features of other
- (ii) the nature of clear and distinct ideas is such that they adequately represent how reality is (or what is really possible).

So Descartes simply denies Arnauld’s premise, that the subject has a clear and distinct idea of a right triangle. If they really did have such an idea, Descartes argues, they would know that the Pythagorean theorem is true of such triangles.

To reject Descartes’s argument we must reject either

- (i) the claim that we (or the Meditator) have clear and distinct ideas of the mind as distinct from the body, or
- (ii) that clear and distinct perception is a reliable guide to real possibility/actuality.
  
***** Causation:

The dualist position articulated here raises problems for D - how do minds and bodies interact, if at all?

- Interactionism
- Occasionalism
- Parallelism





*** Mind-Body dualism
**** Elisabeth
- How could the mind move the body and vice versa?
#+BEGIN_QUOTE
it seems that all determination of movement happens through the impulsion of
the thing moved, by the manner in which it is pushed by that which moves it, or
else by the particular qualities and shape of the surface of the latter.
Physical contact is required for the first two conditions, extension for the
third. (3:661)
#+END_QUOTE 
**** Descartes
- There are 'primitive notions' (i.e. mind, body, and mind-body unity) and we
  cannot expect them to be explicable in any other way than through themselves

#+BEGIN_QUOTE
Although the use of the senses has given us notions of extension, of shapes, and
of movements that are much more familiar than the others, the principal cause of
our errors lies in our ordinarily wanting to use these notions to explain those
things to which they do not pertain. (3:666)
#+END_QUOTE

- We confuse one kind of causation with another

#+BEGIN_QUOTE
I believe that we have heretofore confused the notion of the power with which
the soul acts on the body with the power with which one body acts on another;
and that we have attributed the one and the other not to the soul, for we did
not yet know it, but to diverse qualities of bodies, such as heaviness, heat,
and others, which we have imagined to be real, that is to say, to have an
existence distinct from that of body, and by consequence, to be substances, even
though we have named them qualities. (3:667)
#+END_QUOTE

Garber summarizes this position by saying that 

#+BEGIN_QUOTE
 General notions aside, we have within us three basic ideas, that of mind,
 that of body, and that of their union. Each is separate, each is distinct,
 and each has its own domain of application; each is per se intelligible, and
 cannot be explained in terms of other primitive notions.
#+END_QUOTE

**** Elisabeth
- immateriality is conceivable only as the "negation of matter" (3:684-5)

**** Descartes
- we cannot conceive clearly the mind-body union (3:691-2)
- To think of thought as extended is just to think of the mind-body union (3:694)
- Don't do too much abstract thinking (3:692-3), especially metaphysics (3:695)


**** Three positions on the mind-body relation
1. Interactionism 
2. Occasionalism
3. Parallelism 
   

  

* Week 8 (2/26) 
** Proof of the External world
          
*** The text

The text of the argument is at 7:79

#+BEGIN_QUOTE
  Now there is in me a passive faculty of sensory perception, that is, a
  faculty for receiving and recognizing the ideas of sensible objects;
  but I could not make use of it unless there was also an active
  faculty, either in me or in something else, which produced or brought
  about these ideas. But this faculty cannot be in me, since clearly it
  presupposes no intellectual act on my part, I and the ideas in
  question are produced without my cooperation and often even against my
  will. So the only alternative is that it is in another substance
  distinct from me -- a substance which contains either formally or
  eminently all the reality which exists objectively in the ideas
  produced by this faculty (as I have just noted).

  This substance is either (a) a body, that is, a corporeal nature, in
  which case it will contain formally everything which is to be found
  objectively in the ideas; or else it is (b) God, or some creature more
  noble than a body, in which case it will contain eminently whatever is
  to be found in the ideas.
#+END_QUOTE

Descartes then gives his argument for rejecting (b):

#+BEGIN_QUOTE
  But since God is not a deceiver, it is quite clear that he does not
  transmit the ideas to me either directly from himself, or indirectly,
  via some creature which contains the objective reality of the ideas
  not formally but only eminently. For God has given me no faculty at
  all for recognizing any such source for these ideas; on the contrary,
  he has given me a great propensity to believe that they are produced
  by corporeal things. So I do not see how God could be understood to be
  anything but a deceiver if the ideas were transmitted from a source
  other than corporeal things. It follows that corporeal things exist. (7:79-80)
#+END_QUOTE


*** The Argument:

1. We have sensory ideas, which purport to be of external material things
2. The function of our sensory faculty is to reveal information about our environment
3. Our sensory faculty is passive, so our sensory ideas must come from
   somewhere external to us
4. Sensory ideas come from either (a) bodies or (b) ‘higher’ non-material
   beings (angels, God) [causal principle]
5. If our sensory ideas of bodies were not caused by bodies then God would be
   a deceiver [from 1, 2, 4]
6. God is no deceiver
7. ∴  There exist material bodies that are the causes of our ideas

** Removing the dream doubt (7:89-90)

#+BEGIN_QUOTE
Accordingly, I should not have any further fears about the falsity of what my
senses tell me every day; on the contrary, the exaggerated doubts of the last few
days should be dismissed as laughable. This applies especially to the principal
reason for doubt, namely my inability to distinguish between being asleep and
being awake. For I now notice that there is a vast difference between the two,
in that dreams are never linked by memory with all the other actions of life as
waking experiences are. If, while I am awake, anyone were suddenly to appear to
me and then disappear immediately, as happens in sleep, so that I could not see
where he had 90 come from or where he had gone to, it would not be unreasonable
for me to judge that he was a ghost, or a vision created in my brain, rather
than a real man. But when I distinctly see where things come from and where and
when they come to me, and when I can connect my perceptions of them with the
whole of the rest of my life without a break, then I am quite certain that when
I encounter these things I am not asleep but awake. And I ought not to have even
the slightest doubt of their reality if, after calling upon all the senses as
well as my memory and my intellect in order to check them, I receive no
conflicting reports from any of these sources. For from the fact that God is not
a deceiver it follows that in cases like these I am completely free from error.
(7:89-90)
#+END_QUOTE

So, if the senses, memory, and intellect all confirm the continuity of our
present experience with the past, then, since God is no deceiver, we can safely
be certain that our present situation is not a dream.

*** Objection
 - Couldn’t we feasibly form an extended set of memories in a dream too?

** Wrap-up of Descartes
*** RR Questions

*** Descartes’s Legacy:
**** The Nature of the Subject
- The subject is a /substance/ 
  - The subject is fundamentally active
  - The subject has real and independent causal powers
  - The subject does not inhere in anything (i.e. it is not a property)
    
**** The Centrality of Self-Knowledge
- Immune to skeptical challenge
- Example of a reliable method for acquiring knowledge generally (i.e.
  method of clear & distinct perception)
- Provides us with knowledge of our essence/nature
- Reflection on our nature provides us with the content of various ideas
  necessary for metaphysics (e.g. substance, causation, unity, truth) 
  - Issue of innate ideas -- what exactly are they and in what sens innate?
- The importance of determining what the mind can do/how it can know
  anything for building a stable/reliable science
- Empiricism vs. innate ideas known via reflection alone
    
**** Substance Dualism
- Mind/soul and body are distinct and independent kinds of substance
- Problem of explaining causation in and between minds and bodies

**** Science & Essence
- Knowledge of nature depends on knowledge of essences 
- Knowledge of essences depends on the pure intellect

  
** Mid-term review
*** Discourse on the Method
**** The Method
1. Accept as true only that for which one has proper evidence—viz., clear
   and distinct ideas;
2. Resolve problems into their simplest parts; 
3. Move from the simple and known to the complex; 
4. Thoroughly review and check one’s work to be sure it is comprehensive and
   complete
*** The Meditations
**** Med 1
***** The Project: develop a stable and lasting science
- Develop a science that is "stable and likely to last"
- Epistemic foundationalism :: All knowledge may be divided into two
     classes---basic and derived. Knowledge of the basic truths is immediate
     and non-inferential. All other knowledge is derived from this basic knowledge.
***** The Method of doubt
- We need a reliable method for acquiring knowledge
     - the method of doubt
         - turn us away from the senses as a reliable means of acquiring knowledge
         - emphasis on the pure intellect as the organ by which we acquire knowledge
           
**** Med 2
***** The Cogito
"I exist" is true whenever it is thought

****** Problems:
1. Begs the question
2. Circularity
***** The Wax argument
- Aims to show two things: 
  1. We know things (substances) via the intellect not the senses
  2. The mind is better known than any body
**** Med 3
- The truth rule
  - Truth Rule :: Whenever I C&D perceive then what I perceive is true & I can be certain of it /as such/ 
- The three sources of ideas
- Two proofs of the existence of God
  1. Causal argument
  2. Preservation argument
**** Med 4
- Problem of error
  - error arises due to the combined exercise of the will and intelllect
**** Med 5
***** Knowledge of essences via the intellect
- Primary attribute as essential property of a substance

- essential property :: (i) necessary property of a thing that (ii)
     makes it the kind of thing that it is and (iii) explains other
     properties that a thing may have  


1. Intellectual/intelligible claim: idea of quantity entails other
     ideas (extension entails & is entailed by shape, size, etc)
2. Metaphysical claim : reality is such that if there is extension then
   there is a metaphysical dependence of size, shape, etc., on it 

- We have knowledge of both our own nature and the nature & existence of material bodies

***** Ontological Argument 
- God's essence includes its existence

**** Med 6
- Using C&D method to provide the metaphysical basis for a science of nature
  - Real Distinction arg: there are two kinds of things -- minds & bodies
    - essence of mind is thought
    - essence of body is extension
      - the science of body (physics) is, at its basis, purely intellectual
      - our senses give us knowledge of the practical benefits and perils
        bodies present to us, but they give us only a confused understanding
        of what bodies actually are
  - essences are known through pure reflection - our ideas of essences are innate and furnished to the mind by God
    
*** Correspondence with Elisabeth
**** Elisabeth's objection
- If all motion requires impact then how could an unextended thing ever move
  an extended thing and vice versa?
  
**** Descartes's reply
- Mind, body, and mind-body unity are three "primitive" notions, and we
  shouldn't understand any of the one in the terms set by the other(s)

* Week 9 (3/5)
John Locke (1632-1704)

- Project aims at articulating a theory of the nature and extent of human
  knowledge by way of an examination of the human mind and its powers 


** Locke on Innate Ideas
*** Two versions of nativism
1. Strong: human beings are born with a stock of innate ideas amd
   principles of which they are aware (I.ii.2-5)
2. Weak: "Mature" rational human beings all assent to the same basic
   truths or principles (I.ii.6-14)
*** Objections to Strong Nativism
- Children, "idiots", and "savages" are not aware of, and so lack, any
  plausible candidates for innate ideas (I.ii.5)
*** Objections to Weak Nativism
- It is either false or trivial (I.ii.7)
  1. that as soon as men come to the use of reason these supposedly innate truths come to be known and observed by them
     a. This is false because there are people who have the use of reason
        but don't have the ideas (e.g older children, "savages"; see I.ii.12)
     b. This is trivial (or "frivolous") if it merely means that we can
        learn various, perhaps "self-evident" truths (I.ii.14) 
        - Locke argues that nativists more generally confuse innateness
          with self-evidence at I.ii.18
  2. that the use and exercise of men’s reason assists them in the discovery of these truths, making them known with certainty.
     - This is false because it would mean that anything derived from
       basic innate truths (e.g. the theorems of advanced mathematics)
       would also count as innate, which Locke finds absurd (I.ii.8)
     - Locke also disagrees that the use of reason could be relevant to
       discovery of an idea, since he thinks of reason as moving from
       things known to things that are unknown, and the nativist
       undermines their own position (at least in Locke's eyes) if they
       claim that we don't already have knowledge of our innate ideas (I.ii.9)
** Leibniz on Innate Ideas
Gottfried Wilhelm Leibniz (1646–1716)
*** Ideas as Innate
- not necessary to "have" an idea that one be currently or immediately
  conscious of it
  - memory 
  - complex perceptual experience
  - tacit or potential knowledge 
- One can 'have' an idea by having a particular kind of disposition
  - Is there disagreement between Locke and Leibniz concerning what an 'idea'
    is?
  - Does Locke already allow that some kinds of mental dispositions are innate?


*** In support of dispositional ideas 
**** Memory claim
#+BEGIN_QUOTE
 I am surprised that it has not occurred to you that we know an infinity of
 things which we are not aware of all the time, even when we need them; it is
 the function of memory to store them, and of recollection to put them before
 us again, which it does often - but not always - when there is need for it to
 do so. (I.i.77)
#+END_QUOTE
**** Enthymeme Argument 
- An "enythmeme" is an argument with a "missing" or "suppressed" premise 
  - example: Locke is mortal because he is human
    1. All humans are mortal
    2. Locke is human 
    3. \therefore Locke is mortal 

- Leibniz thinks that when challenged one can supply the missing premise and that this indicates that one "knew" the premise all along 

*** Defense of Innate Ideas
**** Innateness is compatible with
1. our not being aware/conscious of an idea (i.e. ideas as dispositions)
2. the idea's nevertheless being innate in a non-trivial sense. 
**** Marble analogy
#+BEGIN_QUOTE
  if the soul were like these empty tablets, truths would be in us as
  the shape of Hercules is in a block of marble, when the marble is
  completely indifferent to receiving this shape or another. But if the
  stone had veins which marked out the shape of Hercules rather than
  other shapes, then that block would be more determined with respect to
  that shape and Hercules would be as though innate in it in some sense,
  even though some labor would be required for these veins to be exposed
  and polished into clarity by the removal of everything that prevents
  them from appearing. This is how ideas and truths are innate in us, as
  natural inclinations, dispositions, habits, or potentialities
  [virtualites] are, and not as actions are, although these
  potentialities are always accompanied by some corresponding, though
  often insensible, actions. (NE Preface, 294)
#+END_QUOTE



* Week 10 (3/12)

** Quiz
1. T/F: Locke claims that some ideas are innate
   - F
2. Describe one of the versions of nativism discussed by Locke
   - weak/strong 
3. Locke describes two sources of our ideas -- name one 
   - sensation/reflection 
4. T/F: Locke thinks at least some ideas are unconscious
   - F
5. T/F Leibniz suggests that innate ideas are dispositions
   - T
** Leibniz Against Locke on Innateness  
*** Contra Locke on Strong Argument
**** Unconscious ideas
***** Memory
- Locke's argument assumes that all ideas are such that we are aware of them
  but memory shows that this is false (77)
- Memory is an example of the difference between an occurrent state and a disposition

#+BEGIN_QUOTE
 I am surprised that it has not occurred to you that we know an infinity of
 things which we are not aware of all the time, even when we need them; it is
 the function of memory to store them, and of recollection to put them before
 us again, which it does often - but not always - when there is need for it to
 do so. (I.i.77)
#+END_QUOTE

***** Petites Perceptions ("Little/Tiny/Minute Perceptions" pp. 295-6 ) 
- We have perceptions of things that are not apperceived -- they are not the
  objects of memory and attention
  
#+BEGIN_QUOTE
at every moment there is an infinity of perceptions in us, but without
apperception and without reflection-that is, changes in the soul itself, which
we do not consciously perceive [appercevons], because these impressions are
either too small or too numerous, or too homogeneous, in the sense that they
have nothing sufficiently distinct in themselves; but combined with others,
they do have their effect and make themselves felt in the assemblage (/NE
Preface/ in Garber, 295)
#+END_QUOTE



**** Enthymeme argument
Innate ideas are known implicitly or tacitly and function like enthymemes
***** An enthymeme is an argument with a suppressed premise
- e.g. Locke is mortal because he is human
***** When challenged one can supply the missing premise or appeal to the innate idea
*** Contra Locke on Weak Argument
**** Innateness is compatible with 
i. our not being aware of ideas (i.e. ideas being 'in' one dispositionality)
ii. the idea's being "innate" in a non-trivial sense 
**** Marble Analogy (p.  294)
#+BEGIN_QUOTE
I have also used the comparison with a block of veined marble, rather than a
completely uniform block of marble, or an empty tablet, that is, what the
philosophers call a tabula rasa. For if the soul were like these empty
tablets, truths would be in us as the shape of Hercules is in a block of
marble, when the marble is completely indifferent to receiving this shape or
another. But if the stone had veins which marked out the shape of Hercules
rather than other shapes, then that block would be more determined with
respect to that shape and Hercules would be as though innate in it in some
sense, even though some labor would be required for these veins to be exposed
and polished into clarity by the removal of everything that prevents them from
appearing. This is how ideas and truths are innate in us, as natural
inclinations, dispositions, habits, or potentialities [virtualites] are, and
not as actions are, although these potentialities are always accompanied by
some corresponding, though often insensible, actions. (/NE Preface/, Garber p. 294)
#+END_QUOTE

- Does the analogy do enough to assuage Locke's worries about triviality?

*** General Objections
**** Innateness and generality/necessity
- All ideas gained via the senses are /particular/. 
- How could we have ideas of universality and necessity if they came via the
  senses?
**** Personal identity
- On creation, what distinguishes one soul/mind from another? (p. 294)

  
** Mechanism & Materialism
- New model of the natural world and its parts
*** Materialism/Corpuscularianism 
- /metaphysical/ thesis concerning what there is, viz. mind-independent matter
(size, shape, motion, and (perhaps) solidity) and its various combinations
*** Mechanism 
- /explanatory/ thesis concerning how microscopic bodies with size, shape, motion,
etc. interact and explain all manifest properties of macroscopic things -- the
mechanist explains macroscopic things and their features in terms of their parts
 - corpuscles vs. atoms
 - unobservable entities with only geometric/kinetic properties
 - the world as it appears is not the world as it really is

** Galileo on real qualities
- The real qualities of bodies are those without which bodies are inconceivable,
  the rest of the apparent qualities of bodies are really subjective states of
  perceiving subjects
  
*** Determinate vs Determinable Properties
- Distinguish between the determinate properties a thing has, and the
  determinable properties it has. To which does the claim about
  inconceivability apply?

*** Conceivability argument
#+BEGIN_QUOTE
     Now I say that whenever I conceive any material or corporeal substance, I
     immediately feel the need to think of it as bounded, and as having this or
     that shape…[etc.]…From these conditions I cannot separate such a substance
     by any stretch of my imagination. But that it must be white or red, bitter
     or sweet, noisy or silent, and of sweet or foul odor, my mind does not feel
     compelled to bring in as necessary accompaniments. Without the senses as
     our guides, reason or imagination unaided would probably never arrive at
     qualities like these. Hence I think that tastes, odors, colors, and so on
     are no more than mere names so far as the object in which we place them is
     concerned, and that they reside only in the consciousness (Galileo, p.
     274).
#+END_QUOTE


1. Thinking of a material object requires thinking of it as having a particular
   set of qualities (i.e. size, shape, location, motion, etc.)
2. Thinking of a material object does not require thinking of it as having
   specific sensory qualities (e.g. color, taste, smell, sound)
3. The only qualities possessed by a material object are those which we must
   attribute to it in thought
4. ∴ Sensory qualities are not qualities of material objects, but rather
   features of our consciousness of those objects — i.e. “sensations” [from 2, 3]
5. ∴ If there were no conscious beings there would be no sensory qualities (e.g.
   colors, tastes, smells, etc.). [from 4]
  
-  Why should we accept (3)?
    - Descartes gives us one argument for accepting (3) but Galileo provides no
      such epistemological foundation, though he certainly could make use of D's
      system as the backdrop for such an argument

      
*** Eliminativism about sensory qualities
- qualities perceivable only via specific sense modalities (i.e. "proper
  sensibiles" like colors, tastes, and smells)

- Eliminativism about sensory qualities :: all proper sensible qualities are
     merely features of states of consciousness and not features of things
     "in" the world or outside the mind


** Locke's Primary/Secondary distinction

*** Qualities
#+BEGIN_QUOTE
 Whatever the mind perceives in itself—whatever is the immediate object of
 perception, thought, or understanding—I call an idea; and the power to
 produce an idea in our mind I call a quality of the thing that has that
 power (E II.viii.8)
#+END_QUOTE
- Locke, like Aristotle, thinks we can divide the qualities of things into two
  classes: primary & secondary

*** Primary Qualities
#+BEGIN_QUOTE
 Qualities thus considered in bodies are, First, such as are utterly
 inseparable from the body, in what state soever it be; and such as in all the
 alterations and changes it suffers, all the force can be used upon it, it
 constantly keeps; and such as sense constantly finds in every particle of
 matter which has bulk enough to be perceived; and the mind finds inseparable
 from every particle of matter, though less than to make itself singly be
 perceived by our senses: v.g. Take a grain of wheat, divide it into two
 parts; each part has still solidity, extension, figure, and mobility: divide
 it again, and it retains still the same qualities; and so divide it on, till
 the parts become insensible; they must retain still each of them all those
 qualities (II.viii.9)
#+END_QUOTE
**** inseparability argument
1. Every physical change in an object is a change to its determinate qualities
2. Some qualities of bodies are present through all changes---viz., the determinables of size, shape, solidity, and motion
3. ∴ Size, shape, solidity, and motion are inseparable from any existing body

- But why think that some of the qualities are inseparable and others are not?

*** Secondary Qualities
#+BEGIN_QUOTE
 Secondly, [there are qualities] which in truth are nothing in the
 objects themselves but powers to produce various sensations in us by
 their primary qualities, i.e. by the bulk, figure, texture, and
 motion of their insensible parts, as colours, sounds, tastes, &c.
 These I call secondary qualities (II.viii.10, 14, 23).
#+END_QUOTE

- Secondary qualities are "mere powers"
  - colors, tastes, smells

** Problems with Locke's Distinction
- Aren't all qualities powers?
  1. Shape is a primary quality
  2. If shape is a primary quality then it is a quality
  3. Qualities are powers to produce ideas
  4. ∴ Shape is a power to produce an idea—presumably the idea of shape
  5. But secondary qualities are also powers to produce ideas
  6. ∴ There is no primary/secondary distinction between qualities

*** Options for Locke:
A. Deny that primary qualities are “qualities” in Locke’s sense—i.e. deny that there are powers
B. Agree that primary qualities are powers but deny that they are the same sort of power as with secondary qualities
C. Posit that Locke uses “quality” in two different senses:
   - Quality_1: X is a quality_1 iff X is a property
   - Quality_2: X is a quality_2 iff X is a power to cause an idea in one’s mind
D. Maintain that there is only one sense to “quality” but distinguish between real qualities and mere qualities
   - “Real” qualities are qualities which are more than mere powers in things, and exist even in the absence of things they affect
   - “Mere” qualities are no more than powers in things and cease to exist the things they affect are absent

*** Ample textual evidence for (D)
  - II.viii.17; II.viii.24; II.xxxi.2; II.viii.19
  - Are "mere" qualities wholly subjective, as Galileo suggests? – is nothing colored or smelly?

*** Restating the distinction:
- Primary Qualities:
  - Qualities of bodies which are “really” in them in the sense of being both:
    (i) non-relational and (ii) of a determinable which must be had by any
    body (e.g. solidity, extension, size, shape)
- Secondary Qualities:
  - Qualities of bodies, which are “merely” in them, and determined by their
    primary qualities to produce sensory ideas in perceiving subjects. These
    qualities are both (i) relational and (ii) of determinables which need not
    be had by every body (e.g. colors, sounds, tastes)
      
Further, our ideas of primary qualities really "resemble" them while our ideas
of secondary qualities do not (II.viii.15).

*** Three Arguments for Primary/Secondary Distinction 
1) Porphyry Case
2) Almond Case
3) Water Case




** Locke on Real Essence 
*** Locke on Kinds
Locke's view concerning general kinds (e.g. cat, dog, gold) is that there are
no such things that really exist. All there are are particular beings with
some degree or other of resemblance. 

#+BEGIN_QUOTE
it is plain, by what has been said, that general and universal belong not to
the real existence of things; but are the inventions and creatures of the
understanding, made by it for its own use, and concern only signs, whether
words or ideas. (III.iii.11)
#+END_QUOTE

Locke expands on this position slightly. 

#+BEGIN_QUOTE
I would not here be thought to forget, much less to deny, that Nature, in the
production of things, makes several of them alike: there is nothing more
obvious, especially in the race of animals, and all things propagated by seed.
But yet I think we may say, the sorting of them under names is the workmanship
of the understanding, taking occasion, from the similitude it observes amongst
them, to make abstract general ideas, and set them up in the mind, with names
annexed to them, as patterns or forms, (for, in that sense, the word form has
a very proper signification,) to which as particular things existing are found
to agree, so they come to be of that species, have that denomination, or are
put into that /classis/. (III.iii.13)
#+END_QUOTE

There is a bit of a tension here between saying that some things are more
alike than other, but that things do not fall naturally into classes, instead
classes are the "workmanship of the understanding". 

 
*** Role of Essences in Proper Scientific Knowledge
- Scientific knowledge consists in saying why things are the way that
  there are for the members of the given domain.
- Knowledge depends on articulation of real definitions of the subject
  matter of the science, which articulate the essences, or fundamental
  explanatory features, of the relevant individuals studied.

  - /Essences/: individuate kinds, and explain why members of the kind
    have the features that they do.

    - /propria/: necessary but not explanatorily fundamental features
      of a thing---propria may be /inferred/ from the essence
      (risibility in humans).
    - /accidents/: non-necessary and idiosyncratic features of a
      thing---accidents are /not/ inferrable from the essence
      (e.g. the blackness of crows), though they may nevertheless
      /depend/ on the essence.

  - Scientific knowledge depends on articulation of the essences of
    the relevant members in order to provide simple real definitions.

- Scientific definition proceeds by specifying:

  - the kind to which its members belong (/genus/)
  - the name of the thing (/species/) defined by its principle feature
    (/difference/)
  - the characteristics (/properties/) which ‘flow from' that
    principle feature
  - the remaining characteristics which are typical of the thing
    though not inferable from its principle feature (/accidents/)

- A fully articulated proper science would be one which provides a set
  of real definitions of its members from which all the properties have
  been inferred or derived.
  - Euclidean geometry is often taken as an
    exemplar
    - Definition of a circle gives us the essence of the circle from
      which its other properties may be derived/deduced.

#+BEGIN_QUOTE
The conception or definition of the thing must be such that all the
properties of the thing, when regarded by itself and not in conjunction
with other things, can be deduced from it, as can be seen in the case of
this definition of a circle. For from it we clearly deduce that all the
lines drawn from the centre to the circumference are equal. (Spinoza,
/Treatise on the Emendation of the Intellect/, 96)
#+END_QUOTE

*** Real vs. Nominal Essence
Locke distinguishes between two kinds of essence.

#+BEGIN_QUOTE
First, essence may be taken for the very being of any thing, whereby it is
what it is. And thus the real internal, but generally in Substances, unknown
constitution of things, whereon their discoverable qualities depend, may be
called their essence. This is the proper original signiﬁcation of the word. .
. . (Essay III.iii.15) 
#+END_QUOTE

The distinction originally comes from Aristotle, but there concerns
/definitions/. Locke goes on to distinguish the nominal notion of essence in
terms of his conception of nominal kinds. 

#+BEGIN_QUOTE
‘Tis true, there is ordinarily supposed a real constitution of the sorts of
Things; and ‘tis past doubt, there must be some real constitution, on which
any collection of simple Ideas co-existing, must depend. But it being evident,
that Things are ranked under names into sorts or Species, only as they agree
to certain abstract Ideas, to which we have annexed those names, the Essence
of each Genus, or Sort, comes to be nothing but that abstract Idea, which the
general, or Sortal (if I may have leave so to call it from Sort, as I do
General from Genus,) name stands for. and this we shall find to be that which
the word Essence imports, in its most familiar use. These two sorts of
Essences, I suppose, may not unfitly be termed, the one the Real, the other
Nominal Essence. (III.iii.15)
#+END_QUOTE

- Real Essence: :: The property or properties necessary for (i) objectively
                   determining the particular's resemblance relations to other
                   particulars; (ii) upon which many or all of its other
                   monadic properties depend.
- Nominal Essence: :: The property or properties specified by some kind term,
     by which we sort an individual into a particular kind.

  1. We sort things in terms of their nominal, rather than real,
     essences.
  2. We cannot sort things in terms of their real essences.
     
Locke expands on this position. 

#+BEGIN_QUOTE
concerning the real Essences of corporeal Substances, (to mention these only,)
there are, if I mistake not, two Opinions. The one is of those, who using the
word Essence, for they know not what, suppose a certain number of those
Essences, according to which, all natural things are made, and wherein they do
exactly every one of them partake, and so become of this or that Species. The
other, and more rational Opinion, is of those, who look on all natural Things
to have a real, but unknown constitution of their insensible Parts, from which
flow those sensible Qualities, which serve us to distinguish them one from
another, according as we have Occasion to rank them into sorts, under common
denominations. (III.iii.17)
#+END_QUOTE

This might suggest that two particulars might have the same real essence,
which explains why the particulars resemble one another in various ways (as,
e.g., two dogs might resemble one another). But Locke seems to think that no
two real essences are alike. 

#+BEGIN_QUOTE
The frequent Productions of Monsters, in all the Species of animals, and of
changelings, and other strange issues of humane Birth, carry with them
difficulties, not possible to consist with this Hypothesis: Since it is as
impossible, that two Things, partaking exactly of the same real Essence,
should have different Properties, as that two figures partaking of the same
real Essence of a circle, should have different Properties. But were there no
other reason against it, yet the supposition of Essences, that cannot be
known; and the making of them nevertheless to be that, which distinguishes the
Species of Things, is so wholly useless, and unserviceable to any part of our
Knowledge, that that alone were sufficient to make us lay it by; and content
ourselves with such Essences of the Sorts or Species of Things, as come within
the reach of our Knowledge: which, when seriously considered, will be found,
as I have said, to be nothing else, but those abstract complex Ideas, to which
we have annexed distinct general Names. (III.iii.17)
#+END_QUOTE

1. if the real essence of an individual determined its sensible properties, then two individuals with the same real essence should not differ (so much) in their sensible properties
2. “monsters” (offspring that are thought to be of the same real essence as their parents) are occasionally produced in nature
3. ∴ the real essence does not determine sensible properties OR there
   are only particular real essences (i.e. no particulars "share" the
   same real essence)
     
*** Skepticism about (Knowledge of) Essence
Locke gives what sounds like a more epistemic rather than metaphysical
argument concerning the problems with knowing about real essences of things in
III.vi.19

#+BEGIN_QUOTE
The only imaginable help in this case would be, that, having framed perfect
complex ideas of the properties of things flowing from their different real
essences, we should thereby distinguish them into species. But neither can
this be done. For, being ignorant of the real essence itself, it is impossible
to know all those properties that flow from it, and are so annexed to it, that
any one of them being away, we may certainly conclude that that essence is not
there, and so the thing is not of that species. We can never know what is the
precise number of properties depending on the real essence of gold, any one of
which failing, the real essence of gold, and consequently gold, would not be
there, unless we knew the real essence of gold itself, and by that determined
that species. (III.vi.19)
#+END_QUOTE

1. For any object, a proper subset of its monadic properties (the really
   essential properties) explain the instantiation of its other monadic
   properties (its *propria*).
2. We cannot have any epistemic basis for determining which properties are
   really essential without a conception of which *kind* of thing we're
   concerned with.
3. We cannot determine which kind a particular belongs to without a grasp of
   its real essence.
4. \therefore We have no basis for determining the really essential properties of any
   object.


* Week 11 (3/26)
** Locke on Kinds
*** What are kinds?
- examples: cats, dogs, university, cloud, etc.

Kinds are groups whose members are all members in virtue of resembling one
another in some way

"universal" as a entity that unifies all members that share a certain feature. 

*** Locke's denial of kinds
#+BEGIN_QUOTE
I would not here be thought to forget, much less to deny, that Nature, in the
production of things, makes several of them alike: there is nothing more
obvious, especially in the race of animals, and all things propagated by seed.
But yet I think we may say, the sorting of them under names is the workmanship
of the understanding, taking occasion, from the similitude it observes amongst
them, to make abstract general ideas, and set them up in the mind, with names
annexed to them, as patterns or forms, (for, in that sense, the word form has
a very proper signification,) to which as particular things existing are found
to agree, so they come to be of that species, have that denomination, or are
put into that /classis/. (III.iii.13)

#+END_QUOTE

1. Denial of structure in reality -- on Locke's view there are only
   particulars and their properties
2. Advocates "nominalism" about properties 
  - There are no general kinds or universals, there are only our ideas or
    concepts (and their corresponding linguistic expressions)--i.e. "concept
    nominalism" 
    


** Real vs. Nominal Essence
Locke distinguishes between two kinds of essence.

- Real Essence: :: The property or properties that make up the 'real
                   constitution' of a thing and are thus necessary for (i)
                   objectively determining the particular's resemblance
                   relations to other particulars; (ii) upon which many or all
                   of its other properties depend.
- Nominal Essence: :: The property or properties specified by some kind term,
     by which we sort an individual into a particular kind.
     
Locke seems to be making two points in this distinction. 

  1. We sort things in terms of their nominal, rather than real,
     essences.
  2. We cannot sort things in terms of their real essences.
     
     
*** No Two essences are alike
See III.iii.17

1. If the real essence of an individual determined its sensible properties,
   then two individuals with the same real essence should not differ (so much)
   in their sensible properties
2. “Monsters” (i.e. offspring that are thought to be of the same real essence
   as their parents) are occasionally produced in nature
3. ∴ Either real essences do not determine sensible properties OR there
   are only particular real essences (i.e. no particulars "share" the
   same real essence)
     
*** 'Bootstrapping' problem -- Circularity objection
See III.vi.19

2. For any object, a proper subset of its monadic properties (the really
   essential properties) explain the instantiation of its other monadic
   properties (its *propria*).
3. We cannot have any epistemic basis for determining which properties are
   really essential without a conception of which *kind* of thing we're
   concerned with.
4. We cannot determine which kind a particular belongs to without a grasp of
   its real essence.
5. \therefore We have no basis for determining the really essential properties of any
   object.


** Extent of our knowledge

*** No scientific knowledge of nature
We cannot have (demonstrative) scientific knowledge of nature, only morals and
math At best we must be satisfied with ever more justified beliefs, such as
ever more justified versions of the 'corpuscularian hypothesis'

#+BEGIN_QUOTE
  I fear the weakness of human understanding is scarce able to
  substitute another [than the corpuscularian hypothesis], which will
  afford us a fuller and clearer discovery of the necessary connexion
  and coexistence of the powers which are to be observed united in
  several sorts of [bodies]...I doubt whether, with those faculties we
  have, we shall ever be able to carry our general knowledge (I say not
  particular experience) in this part much further. (IV.iii.16)
#+END_QUOTE

*** Challenges for scientific knowledge of nature 

1. Obscurity of essence/real constitution
2. Inscrutability of primary-secondary connection

#+BEGIN_QUOTE
  We are so far from knowing what figure, size, or motion of parts
  produce a yellow colour, a sweet taste, or a sharp sound, that we can
  by no means conceive how any size, figure, or motion of any particles,
  can possibly produce in us the idea of any colour, taste, or sound
  whatsoever: there is no conceivable connexion between the one and the
  other. (IV.iii.13)
#+END_QUOTE

Locke then sums up his argument as follows:

#+BEGIN_QUOTE
  In vain, therefore, shall we endeavour to discover by our ideas (the
  only true way of certain and universal knowledge) what other ideas are
  to be found constantly joined with that of our complex idea of any
  substance: since we (1) neither know the real constitution of the
  minute parts on which their qualities do depend; nor, (2) did we know
  them, could we discover any necessary connexion between them and any
  of the secondary qualities: which is necessary to be done before we
  can certainly know their necessary co-existence. So, that, let our
  complex idea of any species of substances be what it will, we can
  hardly, from the simple ideas contained in it, certainly determine the
  necessary co-existence of any other quality whatsoever. Our knowledge
  in all these inquiries reaches very little further than our
  experience. (IV.iii.14)
#+END_QUOTE

Thus we cannot have scientific knowledge in natural philosophy because
(1) we cannot know the real essences of the minute bodies composing the
observable world, and (2) even if we could know them we could not
discern the necessary connections that exist between those bodies and
their observable secondary qualities. We might summarize these points by
saying that our grasp of the determinate primary qualities of things is
at best obscure, while the connection between these determinate primary
qualities and either determinate or determinable secondary qualities is
completely inscrutable.



* Week 12 (4/2)
** Locke
*** Three features of knowledge
1. Relation between ideas
2. Subject must perceive agreement/disagreement between ideas
3. Knowledge is certain

*** Different Kinds of Knowledge
1. Intuitive knowledge
2. Demonstrative knowledge (anything arrived at via inference)
3. Sensitive knowledge

*** Other kinds of epistemic state
**** Belief
Aims at knowledge but falls short in some way
**** Opinion
Aims at knowledge but falls even further short of some evidential standard
*** Can we have scientific knowledge of nature?
- Corpuscularian hypothesis + Mechanism
  - We can't know that the corpuscularian view is true
    - Obscurity of primary qualities of corpuscles: we can't have knowledge of
      the real essences of the minute material bodies
    - Inscrutability: even if we could know the real essences of individual
      particles the connections between primary and secondary qualities are
      inscrutable to us

      
** Leibniz
*** Against Matter
**** Cartesian substance
1. Individuals (subjects of properties)
2. Independent
**** Matter is not substantial
1. All space is infinitely divisible
2. All bodies are extended in space
3. \therefore All bodies are infinitely divisible 
4. Bodies that are divisible are actually divided -- i.e. have parts
5. What has parts depends for its existence on its parts 
6. \therefore All bodies depend for their existence on their parts 
7. Substance is that which does not depend on anything (except God) for its existence
8. \therefore No material body is a substance 

   
- What about atomism? Leibniz denies that there could be material atoms - why?
  1) atoms are arbitrary -- the nature of materiality is such as to be
     infinitely divisible/divided. It would be contrary to reason (and PSR) to
     stop at some point in the division of matter
  2) atoms are irrelevant -- just because they haven't been divided by
     us doesn't mean that they don't have parts in the relevant sense
