#+TITLE: In-Class Notes
#+OPTIONS: num:nil

* Week 2 (1/15)
** Quiz
1. What are the four rules in Descartes's "method" for acquiring
   knowledge? 
2. What is epistemic foundationalism?
3. (T/F) Descartes's method of doubt requires that we believe all of our beliefs
   are false 
4. Why does Descartes employ his method of doubt?
5. Name one of the stages of doubt

** Scholastic Background
- Cosmology
- Causal structure of nature (4 causes)
- Hylomorphism
- Aristotelian empiricism 
- Demonstrative science (is it possible?)

** Descartes
- Rene Descartes (1596-1650); /Discourse on the Method/ (1637) & The /Meditations/ (1641)

*** The Method

Descartes puts his method this way:

#+BEGIN_QUOTE
The first was never to accept anything as true if I did not have evident
  knowledge of its truth: that is, carefully to avoid precipitate conclusions
  and preconceptions, and to include nothing more in my judgements than what
  presented itself to my mind so clearly and so distinctly that I had no
  occasion to doubt it. 

  The second, to divide each of the difficulties I examined into as many parts
  as possible and as may be required in order to resolve them better.

  The third, to direct my thoughts in an orderly manner, by beginning with the
  simplest and most easily known objects in order to ascend little by little,
  step by step, to knowledge of the most complex, and by supposing some order
  even among objects that have no natural order of precedence.

  And the last, throughout to make enumerations so complete, and reviews so
  comprehensive, that I could be sure of leaving nothing out. (AT VI:18-19)
#+END_QUOTE

We can put the method more concisely as follows:

1. Accept as true only that for which one has proper evidence—viz., clear
   and distinct ideas;
2. Resolve problems into their simplest parts
3. Move from the simple and known to the complex 
4. Thoroughly review and check one’s work to be sure it is comprehensive and complete
 
*** The Meditations

- Meditation as literary form
- Tree metaphor for all human knowledge:
  "The roots are metaphysics, the trunk is physics, and the branches
  emerging from the trunk are all the other sciences, which may be
  reduced to three principal ones, namely medicine, mechanics and
  morals” (AT IXB 14: CSM I 186)


** Meditation 1
***** Structure of Med 1
- The project (7:17-18)
  - Foundationalism :: conception of knowledge as starting from
    absolutely certain first principles, typically known without
    inference from anything else (e.g. they are "self-evident")

  - Method of doubt
    - Suspend judgment concerning all which is uncertain (i.e. all for
      which one can raise some doubt)
  - In particular, doubt /empiricism/
    - Three "stages of doubt" concerning empiricism
      - stage 1: the senses occasionally deceive 
      - stage 2: the dream argument
      - stage 3: the evil demon
- Against Empiricism
  1. Sensory foundations (7:18)
  2. Sensory fallibility (7:18-19)
  3. Objection: Optimal circumstances (7:19)
  4. Objection: Insanity (7:18-19)
  5. The dream argument (7:19)
  6. Objection: The painter’s analogy (7:19-20)
  7. Deceitful God; Dubitability of mathematics (7:21)
  8. The corrective role of doubt (7:22)
  9. The evil demon (7:22-3)

** Meditation 2
*** Structure of Med 2
-   The review of doubt; the *Cogito* (7:24-5)
-   The nature of the 'I' as thinking thing (7:25-7)
-   The mind's unknown relation to body (7:27)
-   The mind itself is not 'imageable' (7:27-8)
-   The variety and unity of thought (7:28-9)
-   The 'Wax Argument' --- our knowledge of body (7:29-33)
-   Analysis of the nature and content of perceptual judgment (7:32)
-   The Mind is better known than (any) body (7:33-4)


*** The Cogito Argument

#+BEGIN_QUOTE
I have convinced myself that there is absolutely nothing in the world, no sky,
no earth, no minds, no bodies. Does it now follow that I too do not exist? No:
if I convinced myself of something then I certainly existed. But there is a
deceiver of supreme power and cunning who is deliberately and constantly
deceiving me. In that case I too undoubtedly exist, if he is deceiving me; and
let him deceive me as much as he can, he will never bring it about that I am
nothing so long as I think that I am something. So after considering
everything very thoroughly, I must finally conclude that this proposition, /I
am, I exist/, is necessarily true whenever it is put forward by me or conceived
in my mind. (7:25)
#+END_QUOTE

**** Problems

- Begs question 
  - 'I' premise assumes existence of subject

- Reformulated argument
  1. A thing is composed of its properties or characteristics /plus/ an
     underlying substance to which they belong
  2. If there is a property or characteristic, then there must be a
     substance to which it belongs.
  3. A thought is a property.
  4. If there is a thought, then there is a substance to which it belongs.
  5. There is a thought.
  6. \therefore There is a substance to which this thought belongs: "I".
* Week 3 (1/22)
- There is no seems/is distinction with respect to certain classes of thought
- How can we be certain that we have the nature that the Meditator claims
  that we have (as thinking substance)? -- Maybe we are just thoughts of the
  "world soul"? 

** Objections (review)
- Begging the question
  - Remove problem by introducing premises?
    1. There is thinking 
    2. For any instantiated property there is a thing---a
       "substance"---that has that property
    3. So there is a thinking thing (1,2)
    4. So I am thinking 
- Invalid argument
  - Can't move from impersonal premises to 1st person conclusion


** A defense
Lichtenberg's objection: "there is no subject of thought -- D's starting
point should be: 'there is thought"

- (T1) It is thought: P
- (T2) It is thought: Q

But then we can't infer from T1 & T2 that

- (T3) It is thought: P & Q

From Lichtenberg's starting point we can't explain the "unity" of thought
-- perhaps this justifies the starting point of Descartes's /Cogito/
argument?

** The Wax Argument

Aims to show two things:
1. the nature of body is known via intellect not senses (7:30-1)
2. the nature of mind is better known than body (7:33)
  
  
*** The Argument
1. I can grasp that this melted wax is flexible and changeable so as to
   be capable of innumerable changes of shape.
2. Imagination could allow me to grasp this fact only by representing
   these changes by an image of each possible shape.
3. My imagination cannot represent the innumerable shapes required.
4. So it is not the imagination that allows me to grasp this capability of
   the wax.
5. But I do grasp this capability, so it must be by a faculty other
   than (sense or) imagination: call it the "intellect".
   

** Quiz
1. What is the "cogito" argument? 
   - "I think, I exist" is true whenever I think it
2. Name one way in which the argument is problematic
   - begs the question 
   - invalid 
3. What does Descartes assume is entailed by the existence of a thought?
   - a thinker (i.e. a substance that has the property of thinking)
4. T/F: The Meditator claims that it can be certain that it is a "thinking
   thing"?
   - T 
5. T/F: The wax argument shows that body is known via the senses only 
   - F
     
** The nature of the subject as a thinking thing
Descartes further understands the 'I' in terms of the kinds of activity
it can undertake. A thinking thing is "a thing that doubts, understands,
affirms, denies, is willing, is unwilling, and also imagines and has
sensory perceptions” (7:28). 

What makes all these characteristic activities go together? 
  - one and same being is *conscious* of engaging in all these kinds of activity

    1. What makes a "mind" a mind?
    2. What are the identity conditions under which a particular mind persists?
** Results of the Cogito
- The results of the Cogito inquiry
  - I am certain that:
    - I exist
    - I exist as a thinking thing
    - A thinking thing is a thing that doubts, understands, affirms, denies, is
      willing or unwilling, imagines, and has sensory perceptions
    - The intellect is an essential feature of a mind, and of all mental
      activities
** Three possible uses of the cogito
1. the 'foundationalist' answer: what is certain is a 'first principle' from
   which we derive other knowledge;
2. the 'systematicity' answer: what is certain is systematically connected with
   other knowledge (e.g. knowledge that 2 + 2 = 4 might be systematically
   related to knowledge that 1 + 1 + 2 = 4, etc.);
3. the 'methodological' answer: what is certain reveal a method for deriving
   other certainties.

** Meditation 3

1. I know with certainty that I am a thinking thing.
2. This knowledge is based solely on a clear and distinct perception of
   its truth. 
3. Clear and distinct perception would not be sufficient to yield such
   knowledge if it were in any way fallible.
4. \therefore Clear and distinct perception provides a sufficient
   ground for knowledge; whatever I so perceive is true.


- Truth Rule :: Whenever I C&D perceive then what I perceive is true & I can be
                certain of it /as such/ 

- *Problem*: could a deceitful god make me go astray even when I have C&D ideas?
* Week 4 (1/29)
** Meditation 3
1. I know with certainty that I am a thinking thing.
2. This knowledge is based solely on a clear and distinct perception of
   its truth. 
3. Clear and distinct perception would not be sufficient to yield such
   knowledge if it were in any way fallible.
4. \therefore Clear and distinct perception provides a sufficient
   ground for knowledge; whatever I so perceive is true.

   

- Truth Rule :: whatever I perceive very clearly and distinctly is true
- *Problem*: could a deceitful god make me go astray even when I have C&D ideas?
  - Reply: We have to (1) examine what ideas are and (2) prove that God exists
    and is no deceiver

*** Ideas
- What are ideas?
  - Mental "representations" :: entities by means of which one is aware of
       things outside or independent of one's mind 

- Two senses of "reality" of idea
  - objective reality :: what the idea is an idea /of/ -- the "content" of
       the idea
  - formal reality :: feature or "mode" of the mind


*** Sources of Ideas
- Where do our ideas (i.e. their content or objective reality) come from?
- Three sources
  1. Adventitious 
  2. Invented/imagined 
  3. Innate 


**** Innate ideas
- What are innate ideas?
  1. An idea one has simply in virtue of having a mind  
  2. An idea gained via reflection on or consciousness of one's nature 
- What, if any, kinds of dependence relations exist between the various
  classes of ideas?


*** Modes of reality
- "Existence" is not "reality"
  - existence appeals to causality/causal effect 
  - reality appeals to power of cause
- Reality as "graded"
  1. Infinite substance   
  2. Finite substance 
  3. Modes (of substance) -- i.e. properties 
*** The Causal Principle
- The causal principle :: there must be at least as much reality in the
     efficient and total cause as in the effect of that cause 
*** Rationalism & the PSR
- Question : why can't something come from nothing?
- Rationalist assumption :: the principles governing the structure
     of nature mirror or are identical with the principles governing
     the structure of our ideas
- The Principle of Sufficient Reason :: For every truth or fact there is a
     sufficient reason

*** The Causal argument
1. The objective reality of an idea must have a cause equal to it or greater
2. The objective reality of my idea of God is that of an omni-omni-omni substance
3. No finite being has sufficient reality to cause the content of my idea of God
4. \therefore The cause of the objective reality of the idea must be God

*** Objections
1. Do we really have such an idea of God?
  - We must because of the "priority of the infinite"

2. Does the idea of God really require an *infinite* cause?
  - No concept of an infinite being could be constructed from finite
    (e.g. sensory) materials

*** Argument for God's existence based on the preservation of finite substance
- /Question/: could I (the meditator) have existed if no "more perfect" being
  existed (7:48) ?
- Four possible sources of my existence:
  1. self-causation
  2. parents
  3. some other finite being
  4. God
- Against (1): only an infinite power could create something from nothing

- Preservation principle :: There is no distinction between preservation
     of existence and creation


1. Any entity that exists exists at discrete moments that are independent of each other
2. The existence of a substance at one moment does not give it the power to
   exist at any other subsequent moment
3. Existence at a moment requires an act equivalent to creation (preservation = creation)
4. No finite entity can create itself
5. ∴ no finite entity can preserve itself from one moment to the next
6. ∴ there must be some entity capable of creation & preservation


** Meditation 4
- God is no deceiver and all-powerful, so why is it that we are created
  with the capacity for error? How is this compatible with the existence
  of a God so conceived?

#+BEGIN_QUOTE
when I concentrate on the nature of God, it seems impossible that he should have
placed in me a faculty which is not perfect of its kind, or which lacks some
perfection which it ought to have...There is, moreover, no doubt that God could
have given me a nature such that I was never mistaken; again, there is no doubt
that he always wills what is best. Is it then better that I should make mistakes
than that I should not do so? (7:55)
#+END_QUOTE

* Week 5 (2/5)
** Quiz
1. Name one source of our ideas that Descartes discusses
   - senses, observation, experience, "adventitious"
   - invented or imagined ideas
   - innate
2. T/F: Descartes needs to prove that God exists to be certain that the
   "cogito" argument is true
   - F
3. T/F: The truth rule states that whenever one thinks, what one thinks is true
   - F
4. T/F: The Med 2 wax argument presupposes that bodies exist
   - F
5. What is the formal reality of an idea?
   - formal reality :: the way an idea exists -- as a mode or property of
                       the mind
   - objective reality :: what the idea is about or represents -- its "content"


** Med 4 - The theory of error

#+BEGIN_QUOTE
I perceive that the power of willing which I received from God is not, when
considered in itself, the cause of my mistakes for it is both extremely ample
and also perfect of its kind. Nor is my power of understanding to blame for
since my understanding comes from God, everything that I understand I
undoubtedly understand correctly, and any error here is impossible. So what then
is the source of my mistakes? It must be simply this: the scope of the will is
wider than that of the intellect; but instead of restricting it within the same
limits, I extend its use to matters which I do not understand. Since the will is
indifferent in such cases, it easily turns aside from what is true and good, and
this is the source of my error and sin. (7:58)
#+END_QUOTE

- The source of error is willing to believe something that is false, or
  for which one lacks sufficient evidence
- We choose or "will" to believe or deny the judgments or ideas presented
  by the understanding  

*** Error as evil -- three responses
1. Maybe we can't always understand God's actions (7:55)
2. Imperfections/evils should be understood at the level of all of creation, not locally
3. In our case, error is the function of a relationship between our faculties


*** Three kinds of causal influence
1. Interactionism
2. Occasionalism
   - direct causal intervention
   - indirect causal intervention via laws of nature
3. Parallelism (divine harmony)
   
   
** Med 5 - Essence & Ontological Argument
1.  Essence of matter is extension (7:63, 71)
2.  Innate ideas of essences (7:63–5)
3.  Ontological argument (7:65–8)


*** Essence of matter
The essence of matter is "continuous quantity" or extension
#+BEGIN_QUOTE
Quantity, for example, or 'continuous' quantity as the philosophers commonly
call it, is something I distinctly imagine. That is, I distinctly imagine the
extension of the quantity (or rather of the thing which is quantified) in
length, breadth and depth. I also enumerate various parts of the thing, and to
these parts I assign various sizes, shapes, positions and local motions; and to
the motions I assign various durations. (7:63)
#+END_QUOTE

*** Extension as "Primary Attribute"
- Primary attribute as essential property of a substance

- essential property :: (i) necessary property of a thing that (ii)
     makes it the kind of thing that it is and (iii) explains other
     properties that a thing may have  

  
1. Intellectual/intelligible claim :: idea of quantity entails other
     ideas (extension entails & is entailed by shape, size, etc)
2. Metaphysical claim : reality is such that if there is extension then
   there is a metaphysical dependence of size, shape, etc., on it 
     



*** The ontological argument
1. Whatever I C+D perceive to belong to the essence of a thing does
2. I C+D perceive that the essence of God includes every perfection
3. It is more perfect to exist than not to existence (existence is a perfection)
4. \therefore Existence is necessarily part of God's essence
5. \therefore God necessarily exists


*** Objections
1. We don't have a C+D perception of God's essence, which means we don't
   have a C+D perception of whether that essence includes existence 
2. Why think that existence is a perfection?
   - maybe "exist" doesn't pick out a property in anything like the way
     "hot" or "good" does -- "existence" isn't a "real predicate" 
   
     
* Week 6 (2/12)
** Quiz
1. In Med 3 Descartes articulates 2 proofs of the existence of God. Name one.
   - casual argument from idea of God
   - preservation/creation of finite beings
2. In his first proof of God’s existence D uses a metaphysical principle. Name
   the principle & briefly describe its content
   - Causal principle
3. T/F: Descartes explains the existence of error as arising because of the
   relation between the imagination and the understanding
   - F
4. T/F: Descartes thinks that finite substances lack the power to persist
   through time on their own 
   - T
5. T/F: Descartes thinks that the power to preserve is the same the as the power
   to create
   - T

** The "Cartesian Circle"
1. I can be certain of P only if I am certain that Q
2. I can be certain of Q only if I am certain that P

P: whatever I perceive clearly and distinctly is true
Q: God exists and is not a deceiver

How does Descartes avoid the circular reasoning? Can he deny either or
both of (1) or (2)?
** Descartes's Memory Response
- We don't need proof of God's existence and non-deceitful nature to certify
  C&D perception, rather only need proof of God to show that we can rely on
  memory of C&D perception
- Worry: doesn't really answer the fundamental objection that we need some
  certification for C&D perception /itself/.
** Alternative Strategies for resolving the Circle
*** 1. Mere psychological certainty not truth
- Maybe Descartes is just after unshakable psychological certainty or
  conviction rather than truth
- Unsatisfying as a general explanation of what Descartes is doing in
  the Meditations (e.g. unsatisfying as explanation of Med 5 argument
  concerning our intellectual grasp of essences)
*** 2. Remove the doubt
Descartes isn't trying to prove that C&D perception is /true/, only that
we have no defensible grounds for doubting C&D perception 

- Maybe not going to work since even just removing doubt about decietful
  god via appeal to our idea of God will rely on C&D perception of the
  content of our idea of God
- Doesn't seem to remove grounds for doubting a "defective origins"
  style objection as from Med 1 (7:21)
  
**** Two Validation Projects
***** Strong Validation of the Intellect
The intellect is capable of discovering and knowing/justifying
metaphysical principles concerning reality
***** Weak Validation of the Intellect 
There are no good grounds for doubting the deliverances of the
intellect -- it is a (generally) reliable faculty for knowledge 
*** 3. Presumption in favor of the intellect
Why couldn't the Meditator reasonably begin with the presumption of the
reliability of the human intellect?

- Worry: begs the question against those who doubt the power/reliability
  of intellect
- Worry: doesn't account for how we can have knowledge of essences of
  real objects (e.g. knowledge of essence of matter or God)


** Is the Circle  Inescapable?
- If D is after a "strong validation" of the intellect then he may be
  unable to escape the circle since he would need positive proof that the
  method of C&D perception is reliable but his only such positive proofs
  (e.g. God's existence) rely on that very method


** Is Descartes's Problem our Problem?
- "Problem of the criterion" :: whether or not we need to know the epistemic principles which justify our claims to knowledge prior to (and perhaps independently of) any knowledge that we have, including knowledge that might be necessary for formulating the principles.
  

  
  
** Meditation 6

*** Three kinds of distinctness
1. conceptual
- distinction necessary for the intelligibility of something 
2. modal
- distinction between properties or modes, but not between things 
3. real 
- distinction between existing things (applies only to substance) --
  specifically that they /could/ exist independent of one another (whether
  they actually do or not). 

  
*** The real distinction argument
**** Three claims
- Complete Being_T :: a thinking thing can exist as a substance whose sole
     essence is thought.
- Complete Being_B :: body can exist as a substance whose sole essence is extension.
- Mutual Exclusion :: mental substance has no bodily modes, and bodily substance has no mental modes.
     
***** God's power
Part [A] says:

#+BEGIN_QUOTE
  [A] I know that everything which I clearly and distinctly understand
  is capable of being created by God so as to correspond exactly with my
  understanding of it. Hence the fact that I can clearly and distinctly
  understand one thing apart from another is enough to make me certain
  that the two things are distinct, since they are capable of being
  separated, at least by God. The question of what kind of power is
  required to bring about such a separation does not affect the
  judgement that the two things are distinct.
#+END_QUOTE

Here is what part A [[http://plato.stanford.edu/entries/descartes-modal/#ReaDis][seems to be arguing]]:

1. I clearly and distinctly understand mind apart from body and body
   apart from mind.
2. God can bring about whatever I clearly and distinctly perceive.
3. God can bring about that mind is apart from body and body is apart
   from mind.
4. If God can bring about that mind is apart from body and body is apart
   from mind, then mind and body can exist apart.
5. \therefore Mind and body can exist apart.
   
   - How do we know that we are C&D perceiving mind apart from body,
     etc.? 

   - What we would want is a *natural* distinction between mind &
     body, not a *supernatural* or *miraculous* distinction
     

***** Knowing one's essence
#+BEGIN_QUOTE
  [B] Thus, simply by knowing that I exist and seeing at the same time
  that absolutely nothing else belongs to my nature or essence except
  that I am a thinking thing, I can infer correctly that my essence
  consists solely in the fact that I am a thinking thing. 
#+END_QUOTE

1. One's self exists
2. Nothing belongs to one’s essence or nature other than thinking
3. ∴ All properties of oneself have to be conceived via this essence – thought

Is this argument enough to yield the Real Distinction? Presumably not – it just tells us that our essence is that of a thinking being, it doesn’t tell us that all thinking beings are independent of any body. It doesn’t give us Mutual Exclusion. But it does give us Complete Being-T.

***** Real distinctness
#+BEGIN_QUOTE
  [C] It is true that I may have (or, to anticipate, that I certainly have) a
  body that is very closely joined to me. But nevertheless, on the one hand I
  have a clear and distinct idea of myself, in so far as I am simply a
  thinking, non-extended thing; and on the other hand I have a distinct idea
  of body, in so far as this is simply an extended, non-thinking thing. And
  accordingly, it is certain that I am really distinct from my body, and can
  exist without it.
#+END_QUOTE

According to the Meditator's distinct and clear ideas:

1. The self is a thinking and non-extended thing
2. Corporeal substance is extended and non-thinking

This gives us /Mutual Exclusion/. If we assume Complete Being_B then it seems D gives us what we need to conclude that mind and body are Really Distinct

- Is it clear that if a thing can exist that has no bodily properties then that thing can exist apart from bodies?
  - could there be some other kind of dependence relation between minds and bodies apart from modal/property dependence?
    - not, presumably, if we are talking about substances, since substances are independent beings

***** Objections 
- How do we know that the apparent distinctness of mind and body is not due to our ignorance of their real identity?

#+BEGIN_QUOTE
  Suppose someone knows for certain that the angle in a semi-circle is a
  right angle, and hence that the triangle formed by this angle and the
  diameter of the circle is right-angled. In spite of this, he may
  doubt, or not yet have grasped for certain, that the square on the
  hypotenuse is equal to the squares on the other two sides; indeed he
  may even deny this if he is misled by some fallacy. But now, if he
  uses the same argument as that proposed by our illustrious author, he
  may appear to have confirmation of his false belief, as follows: 'I
  clearly and distinctly perceive', he may say, 'that the triangle is
  right-angled; but I doubt that the square on the hypotenuse is equal
  to the squares on the other two sides; therefore it does not belong to
  the essence of the triangle that the square on its hypotenuse is equal
  to the squares on the other sides.' (7:201-2)
#+END_QUOTE

Descartes’s answer, perhaps unsurprisingly, refers to what the Meditator has learned so far

- (i) the fact that the Meditator has clear and distinct ideas of mind and body, where each excludes the features of other
- (ii) the nature of clear and distinct ideas is such that they adequately represent how reality is (or what is really possible).

So Descartes simply denies Arnauld’s premise, that the subject has a clear and distinct idea of a right triangle. If they really did have such an idea, Descartes argues, they would know that the Pythagorean theorem is true of such triangles.

To reject Descartes’s argument we must reject either

- (i) the claim that we (or the Meditator) have clear and distinct ideas of the mind as distinct from the body, or
- (ii) that clear and distinct perception is a reliable guide to real possibility/actuality.
  
***** Causation:

The dualist position articulated here raises problems for D - how do minds and bodies interact, if at all?

- Interactionism
- Occasionalism
- Parallelism


* Week 7 (2/19)
*** The real distinction argument
**** Three claims
- Complete Being_T :: a thinking thing can exist as a substance whose sole
     essence is thought.
- Complete Being_B :: body can exist as a substance whose sole essence is extension.
- Mutual Exclusion :: mental substance has no bodily modes, and bodily substance has no mental modes.
     
***** God's power
Part [A] says:

#+BEGIN_QUOTE
  [A] I know that everything which I clearly and distinctly understand
  is capable of being created by God so as to correspond exactly with my
  understanding of it. Hence the fact that I can clearly and distinctly
  understand one thing apart from another is enough to make me certain
  that the two things are distinct, since they are capable of being
  separated, at least by God. The question of what kind of power is
  required to bring about such a separation does not affect the
  judgement that the two things are distinct.
#+END_QUOTE

Here is what part A [[http://plato.stanford.edu/entries/descartes-modal/#ReaDis][seems to be arguing]]:

1. I clearly and distinctly understand mind apart from body and body
   apart from mind.
2. God can bring about whatever I clearly and distinctly perceive.
3. God can bring about that mind is apart from body and body is apart
   from mind.
4. If God can bring about that mind is apart from body and body is apart
   from mind, then mind and body can exist apart.
5. \therefore Mind and body can exist apart.
   
- We want to know whether mind and body naturally exist apart, not whether God can miraculously separate them…

***** Knowing one's essence
#+BEGIN_QUOTE
  [B] Thus, simply by knowing that I exist and seeing at the same time
  that absolutely nothing else belongs to my nature or essence except
  that I am a thinking thing, I can infer correctly that my essence
  consists solely in the fact that I am a thinking thing. 
#+END_QUOTE

1. One's self exists
2. Nothing belongs to one’s essence or nature other than thinking
3. ∴ All properties of oneself have to be conceived via this essence – thought

Is this argument enough to yield the Real Distinction? Presumably not – it just tells us that our essence is that of a thinking being, it doesn’t tell us that all thinking beings are independent of any body. It doesn’t give us Mutual Exclusion. But it does give us Complete Being-T.

***** Real distinctness
#+BEGIN_QUOTE
  [C] It is true that I may have (or, to anticipate, that I certainly have) a
  body that is very closely joined to me. But nevertheless, on the one hand I
  have a clear and distinct idea of myself, in so far as I am simply a
  thinking, non-extended thing; and on the other hand I have a distinct idea
  of body, in so far as this is simply an extended, non-thinking thing. And
  accordingly, it is certain that I am really distinct from my body, and can
  exist without it.
#+END_QUOTE

According to the Meditator's distinct and clear ideas:

1. The self is a thinking and non-extended thing
2. Corporeal substance is extended and non-thinking

This gives us /Mutual Exclusion/. If we assume Complete Being_B then it seems D gives us what we need to conclude that mind and body are Really Distinct

- Is it clear that if a thing can exist that has no bodily properties then that thing can exist apart from bodies?
  - could there be some other kind of dependence relation between minds and bodies apart from modal/property dependence?
    - not, presumably, if we are talking about substances, since substances are independent beings

***** Objections 
- How do we know that the apparent distinctness of mind and body is not due to our ignorance of their real identity?

#+BEGIN_QUOTE
  Suppose someone knows for certain that the angle in a semi-circle is a
  right angle, and hence that the triangle formed by this angle and the
  diameter of the circle is right-angled. In spite of this, he may
  doubt, or not yet have grasped for certain, that the square on the
  hypotenuse is equal to the squares on the other two sides; indeed he
  may even deny this if he is misled by some fallacy. But now, if he
  uses the same argument as that proposed by our illustrious author, he
  may appear to have confirmation of his false belief, as follows: 'I
  clearly and distinctly perceive', he may say, 'that the triangle is
  right-angled; but I doubt that the square on the hypotenuse is equal
  to the squares on the other two sides; therefore it does not belong to
  the essence of the triangle that the square on its hypotenuse is equal
  to the squares on the other sides.' (7:201-2)
#+END_QUOTE

Descartes’s answer, perhaps unsurprisingly, refers to what the Meditator has learned so far

- (i) the fact that the Meditator has clear and distinct ideas of mind and body, where each excludes the features of other
- (ii) the nature of clear and distinct ideas is such that they adequately represent how reality is (or what is really possible).

So Descartes simply denies Arnauld’s premise, that the subject has a clear and distinct idea of a right triangle. If they really did have such an idea, Descartes argues, they would know that the Pythagorean theorem is true of such triangles.

To reject Descartes’s argument we must reject either

- (i) the claim that we (or the Meditator) have clear and distinct ideas of the mind as distinct from the body, or
- (ii) that clear and distinct perception is a reliable guide to real possibility/actuality.
  
***** Causation:

The dualist position articulated here raises problems for D - how do minds and bodies interact, if at all?

- Interactionism
- Occasionalism
- Parallelism





*** Mind-Body dualism
**** Elisabeth
- How could the mind move the body and vice versa?
#+BEGIN_QUOTE
it seems that all determination of movement happens through the impulsion of
the thing moved, by the manner in which it is pushed by that which moves it, or
else by the particular qualities and shape of the surface of the latter.
Physical contact is required for the first two conditions, extension for the
third. (3:661)
#+END_QUOTE 
**** Descartes
- There are 'primitive notions' (i.e. mind, body, and mind-body unity) and we
  cannot expect them to be explicable in any other way than through themselves

#+BEGIN_QUOTE
Although the use of the senses has given us notions of extension, of shapes, and
of movements that are much more familiar than the others, the principal cause of
our errors lies in our ordinarily wanting to use these notions to explain those
things to which they do not pertain. (3:666)
#+END_QUOTE

- We confuse one kind of causation with another

#+BEGIN_QUOTE
I believe that we have heretofore confused the notion of the power with which
the soul acts on the body with the power with which one body acts on another;
and that we have attributed the one and the other not to the soul, for we did
not yet know it, but to diverse qualities of bodies, such as heaviness, heat,
and others, which we have imagined to be real, that is to say, to have an
existence distinct from that of body, and by consequence, to be substances, even
though we have named them qualities. (3:667)
#+END_QUOTE

Garber summarizes this position by saying that 

#+BEGIN_QUOTE
 General notions aside, we have within us three basic ideas, that of mind,
 that of body, and that of their union. Each is separate, each is distinct,
 and each has its own domain of application; each is per se intelligible, and
 cannot be explained in terms of other primitive notions.
#+END_QUOTE

**** Elisabeth
- immateriality is conceivable only as the "negation of matter" (3:684-5)

**** Descartes
- we cannot conceive clearly the mind-body union (3:691-2)
- To think of thought as extended is just to think of the mind-body union (3:694)
- Don't do too much abstract thinking (3:692-3), especially metaphysics (3:695)


**** Three positions on the mind-body relation
1. Interactionism 
2. Occasionalism
3. Parallelism 
   

  

* Week 8 (2/26) 
** Proof of the External world
          
*** The text

The text of the argument is at 7:79

#+BEGIN_QUOTE
  Now there is in me a passive faculty of sensory perception, that is, a
  faculty for receiving and recognizing the ideas of sensible objects;
  but I could not make use of it unless there was also an active
  faculty, either in me or in something else, which produced or brought
  about these ideas. But this faculty cannot be in me, since clearly it
  presupposes no intellectual act on my part, I and the ideas in
  question are produced without my cooperation and often even against my
  will. So the only alternative is that it is in another substance
  distinct from me -- a substance which contains either formally or
  eminently all the reality which exists objectively in the ideas
  produced by this faculty (as I have just noted).

  This substance is either (a) a body, that is, a corporeal nature, in
  which case it will contain formally everything which is to be found
  objectively in the ideas; or else it is (b) God, or some creature more
  noble than a body, in which case it will contain eminently whatever is
  to be found in the ideas.
#+END_QUOTE

Descartes then gives his argument for rejecting (b):

#+BEGIN_QUOTE
  But since God is not a deceiver, it is quite clear that he does not
  transmit the ideas to me either directly from himself, or indirectly,
  via some creature which contains the objective reality of the ideas
  not formally but only eminently. For God has given me no faculty at
  all for recognizing any such source for these ideas; on the contrary,
  he has given me a great propensity to believe that they are produced
  by corporeal things. So I do not see how God could be understood to be
  anything but a deceiver if the ideas were transmitted from a source
  other than corporeal things. It follows that corporeal things exist. (7:79-80)
#+END_QUOTE


*** The Argument:

1. We have sensory ideas, which purport to be of external material things
2. The function of our sensory faculty is to reveal information about our environment
3. Our sensory faculty is passive, so our sensory ideas must come from
   somewhere external to us
4. Sensory ideas come from either (a) bodies or (b) ‘higher’ non-material
   beings (angels, God) [causal principle]
5. If our sensory ideas of bodies were not caused by bodies then God would be
   a deceiver [from 1, 2, 4]
6. God is no deceiver
7. ∴  There exist material bodies that are the causes of our ideas

** Removing the dream doubt (7:89-90)

#+BEGIN_QUOTE
Accordingly, I should not have any further fears about the falsity of what my
senses tell me every day; on the contrary, the exaggerated doubts of the last few
days should be dismissed as laughable. This applies especially to the principal
reason for doubt, namely my inability to distinguish between being asleep and
being awake. For I now notice that there is a vast difference between the two,
in that dreams are never linked by memory with all the other actions of life as
waking experiences are. If, while I am awake, anyone were suddenly to appear to
me and then disappear immediately, as happens in sleep, so that I could not see
where he had 90 come from or where he had gone to, it would not be unreasonable
for me to judge that he was a ghost, or a vision created in my brain, rather
than a real man. But when I distinctly see where things come from and where and
when they come to me, and when I can connect my perceptions of them with the
whole of the rest of my life without a break, then I am quite certain that when
I encounter these things I am not asleep but awake. And I ought not to have even
the slightest doubt of their reality if, after calling upon all the senses as
well as my memory and my intellect in order to check them, I receive no
conflicting reports from any of these sources. For from the fact that God is not
a deceiver it follows that in cases like these I am completely free from error.
(7:89-90)
#+END_QUOTE

So, if the senses, memory, and intellect all confirm the continuity of our
present experience with the past, then, since God is no deceiver, we can safely
be certain that our present situation is not a dream.

*** Objection
 - Couldn’t we feasibly form an extended set of memories in a dream too?

** Wrap-up of Descartes
*** RR Questions

*** Descartes’s Legacy:
**** The Nature of the Subject
- The subject is a /substance/ 
  - The subject is fundamentally active
  - The subject has real and independent causal powers
  - The subject does not inhere in anything (i.e. it is not a property)
    
**** The Centrality of Self-Knowledge
- Immune to skeptical challenge
- Example of a reliable method for acquiring knowledge generally (i.e.
  method of clear & distinct perception)
- Provides us with knowledge of our essence/nature
- Reflection on our nature provides us with the content of various ideas
  necessary for metaphysics (e.g. substance, causation, unity, truth) 
  - Issue of innate ideas -- what exactly are they and in what sens innate?
- The importance of determining what the mind can do/how it can know
  anything for building a stable/reliable science
- Empiricism vs. innate ideas known via reflection alone
    
**** Substance Dualism
- Mind/soul and body are distinct and independent kinds of substance
- Problem of explaining causation in and between minds and bodies

**** Science & Essence
- Knowledge of nature depends on knowledge of essences 
- Knowledge of essences depends on the pure intellect

  
** Mid-term review
*** Discourse on the Method
**** The Method
1. Accept as true only that for which one has proper evidence—viz., clear
   and distinct ideas;
2. Resolve problems into their simplest parts; 
3. Move from the simple and known to the complex; 
4. Thoroughly review and check one’s work to be sure it is comprehensive and
   complete
*** The Meditations
**** Med 1
***** The Project: develop a stable and lasting science
- Develop a science that is "stable and likely to last"
- Epistemic foundationalism :: All knowledge may be divided into two
     classes---basic and derived. Knowledge of the basic truths is immediate
     and non-inferential. All other knowledge is derived from this basic knowledge.
***** The Method of doubt
- We need a reliable method for acquiring knowledge
     - the method of doubt
         - turn us away from the senses as a reliable means of acquiring knowledge
         - emphasis on the pure intellect as the organ by which we acquire knowledge
           
**** Med 2
***** The Cogito
"I exist" is true whenever it is thought

****** Problems:
1. Begs the question
2. Circularity
***** The Wax argument
- Aims to show two things: 
  1. We know things (substances) via the intellect not the senses
  2. The mind is better known than any body
**** Med 3
- The truth rule
  - Truth Rule :: Whenever I C&D perceive then what I perceive is true & I can be certain of it /as such/ 
- The three sources of ideas
- Two proofs of the existence of God
  1. Causal argument
  2. Preservation argument
**** Med 4
- Problem of error
  - error arises due to the combined exercise of the will and intelllect
**** Med 5
***** Knowledge of essences via the intellect
- Primary attribute as essential property of a substance

- essential property :: (i) necessary property of a thing that (ii)
     makes it the kind of thing that it is and (iii) explains other
     properties that a thing may have  


1. Intellectual/intelligible claim: idea of quantity entails other
     ideas (extension entails & is entailed by shape, size, etc)
2. Metaphysical claim : reality is such that if there is extension then
   there is a metaphysical dependence of size, shape, etc., on it 

- We have knowledge of both our own nature and the nature & existence of material bodies

***** Ontological Argument 
- God's essence includes its existence

**** Med 6
- Using C&D method to provide the metaphysical basis for a science of nature
  - Real Distinction arg: there are two kinds of things -- minds & bodies
    - essence of mind is thought
    - essence of body is extension
      - the science of body (physics) is, at its basis, purely intellectual
      - our senses give us knowledge of the practical benefits and perils
        bodies present to us, but they give us only a confused understanding
        of what bodies actually are
  - essences are known through pure reflection - our ideas of essences are innate and furnished to the mind by God
    
*** Correspondence with Elisabeth
**** Elisabeth's objection
- If all motion requires impact then how could an unextended thing ever move
  an extended thing and vice versa?
  
**** Descartes's reply
- Mind, body, and mind-body unity are three "primitive" notions, and we
  shouldn't understand any of the one in the terms set by the other(s)

