#+TITLE: In-Class Notes

* Week 2 (1/15)
** Quiz
1. What are the four rules in Descartes's "method" for acquiring
   knowledge? 
2. What is epistemic foundationalism?
3. (T/F) Descartes's method of doubt requires that we believe all of our beliefs
   are false 
4. Why does Descartes employ his method of doubt?
5. Name one of the stages of doubt

** Scholastic Background
- Cosmology
- Causal structure of nature (4 causes)
- Hylomorphism
- Aristotelian empiricism 
- Demonstrative science (is it possible?)

** Descartes
- Rene Descartes (1596-1650); /Discourse on the Method/ (1637) & The /Meditations/ (1641)

*** The Method

Descartes puts his method this way:

#+BEGIN_QUOTE
The first was never to accept anything as true if I did not have evident
  knowledge of its truth: that is, carefully to avoid precipitate conclusions
  and preconceptions, and to include nothing more in my judgements than what
  presented itself to my mind so clearly and so distinctly that I had no
  occasion to doubt it. 

  The second, to divide each of the difficulties I examined into as many parts
  as possible and as may be required in order to resolve them better.

  The third, to direct my thoughts in an orderly manner, by beginning with the
  simplest and most easily known objects in order to ascend little by little,
  step by step, to knowledge of the most complex, and by supposing some order
  even among objects that have no natural order of precedence.

  And the last, throughout to make enumerations so complete, and reviews so
  comprehensive, that I could be sure of leaving nothing out. (AT VI:18-19)
#+END_QUOTE

We can put the method more concisely as follows:

1. Accept as true only that for which one has proper evidence—viz., clear
   and distinct ideas;
2. Resolve problems into their simplest parts
3. Move from the simple and known to the complex 
4. Thoroughly review and check one’s work to be sure it is comprehensive and complete
 
*** The Meditations

- Meditation as literary form
- Tree metaphor for all human knowledge:
  "The roots are metaphysics, the trunk is physics, and the branches
  emerging from the trunk are all the other sciences, which may be
  reduced to three principal ones, namely medicine, mechanics and
  morals” (AT IXB 14: CSM I 186)


** Meditation 1
***** Structure of Med 1
- The project (7:17-18)
  - Foundationalism :: conception of knowledge as starting from
    absolutely certain first principles, typically known without
    inference from anything else (e.g. they are "self-evident")

  - Method of doubt
    - Suspend judgment concerning all which is uncertain (i.e. all for
      which one can raise some doubt)
  - In particular, doubt /empiricism/
    - Three "stages of doubt" concerning empiricism
      - stage 1: the senses occasionally deceive 
      - stage 2: the dream argument
      - stage 3: the evil demon
- Against Empiricism
  1. Sensory foundations (7:18)
  2. Sensory fallibility (7:18-19)
  3. Objection: Optimal circumstances (7:19)
  4. Objection: Insanity (7:18-19)
  5. The dream argument (7:19)
  6. Objection: The painter’s analogy (7:19-20)
  7. Deceitful God; Dubitability of mathematics (7:21)
  8. The corrective role of doubt (7:22)
  9. The evil demon (7:22-3)

** Meditation 2
*** Structure of Med 2
-   The review of doubt; the *Cogito* (7:24-5)
-   The nature of the 'I' as thinking thing (7:25-7)
-   The mind's unknown relation to body (7:27)
-   The mind itself is not 'imageable' (7:27-8)
-   The variety and unity of thought (7:28-9)
-   The 'Wax Argument' --- our knowledge of body (7:29-33)
-   Analysis of the nature and content of perceptual judgment (7:32)
-   The Mind is better known than (any) body (7:33-4)


*** The Cogito Argument

#+BEGIN_QUOTE
I have convinced myself that there is absolutely nothing in the world, no sky,
no earth, no minds, no bodies. Does it now follow that I too do not exist? No:
if I convinced myself of something then I certainly existed. But there is a
deceiver of supreme power and cunning who is deliberately and constantly
deceiving me. In that case I too undoubtedly exist, if he is deceiving me; and
let him deceive me as much as he can, he will never bring it about that I am
nothing so long as I think that I am something. So after considering
everything very thoroughly, I must finally conclude that this proposition, /I
am, I exist/, is necessarily true whenever it is put forward by me or conceived
in my mind. (7:25)
#+END_QUOTE

**** Problems

- Begs question 
  - 'I' premise assumes existence of subject

- Reformulated argument
  1. A thing is composed of its properties or characteristics /plus/ an
     underlying substance to which they belong
  2. If there is a property or characteristic, then there must be a
     substance to which it belongs.
  3. A thought is a property.
  4. If there is a thought, then there is a substance to which it belongs.
  5. There is a thought.
  6. \therefore There is a substance to which this thought belongs: "I".
* Week 3 (1/22)
- There is no seems/is distinction with respect to certain classes of thought
- How can we be certain that we have the nature that the Meditator claims
  that we have (as thinking substance)? -- Maybe we are just thoughts of the
  "world soul"? 

** Objections (review)
- Begging the question
  - Remove problem by introducing premises?
    1. There is thinking 
    2. For any instantiated property there is a thing---a
       "substance"---that has that property
    3. So there is a thinking thing (1,2)
    4. So I am thinking 
- Invalid argument
  - Can't move from impersonal premises to 1st person conclusion


** A defense
Lichtenberg's objection: "there is no subject of thought -- D's starting
point should be: 'there is thought"

- (T1) It is thought: P
- (T2) It is thought: Q

But then we can't infer from T1 & T2 that

- (T3) It is thought: P & Q

From Lichtenberg's starting point we can't explain the "unity" of thought
-- perhaps this justifies the starting point of Descartes's /Cogito/
argument?

** The Wax Argument

Aims to show two things:
1. the nature of body is known via intellect not senses (7:30-1)
2. the nature of mind is better known than body (7:33)
  
  
*** The Argument
1. I can grasp that this melted wax is flexible and changeable so as to
   be capable of innumerable changes of shape.
2. Imagination could allow me to grasp this fact only by representing
   these changes by an image of each possible shape.
3. My imagination cannot represent the innumerable shapes required.
4. So it is not the imagination that allows me to grasp this capability of
   the wax.
5. But I do grasp this capability, so it must be by a faculty other
   than (sense or) imagination: call it the "intellect".
   

** Quiz
1. What is the "cogito" argument? 
   - "I think, I exist" is true whenever I think it
2. Name one way in which the argument is problematic
   - begs the question 
   - invalid 
3. What does Descartes assume is entailed by the existence of a thought?
   - a thinker (i.e. a substance that has the property of thinking)
4. T/F: The Meditator claims that it can be certain that it is a "thinking
   thing"?
   - T 
5. T/F: The wax argument shows that body is known via the senses only 
   - F
     
** The nature of the subject as a thinking thing
Descartes further understands the 'I' in terms of the kinds of activity
it can undertake. A thinking thing is "a thing that doubts, understands,
affirms, denies, is willing, is unwilling, and also imagines and has
sensory perceptions” (7:28). 

What makes all these characteristic activities go together? 
  - one and same being is *conscious* of engaging in all these kinds of activity

    1. What makes a "mind" a mind?
    2. What are the identity conditions under which a particular mind persists?
** Results of the Cogito
- The results of the Cogito inquiry
  - I am certain that:
    - I exist
    - I exist as a thinking thing
    - A thinking thing is a thing that doubts, understands, affirms, denies, is
      willing or unwilling, imagines, and has sensory perceptions
    - The intellect is an essential feature of a mind, and of all mental
      activities
** Three possible uses of the cogito
1. the 'foundationalist' answer: what is certain is a 'first principle' from
   which we derive other knowledge;
2. the 'systematicity' answer: what is certain is systematically connected with
   other knowledge (e.g. knowledge that 2 + 2 = 4 might be systematically
   related to knowledge that 1 + 1 + 2 = 4, etc.);
3. the 'methodological' answer: what is certain reveal a method for deriving
   other certainties.

** Meditation 3

1. I know with certainty that I am a thinking thing.
2. This knowledge is based solely on a clear and distinct perception of
   its truth. 
3. Clear and distinct perception would not be sufficient to yield such
   knowledge if it were in any way fallible.
4. \therefore Clear and distinct perception provides a sufficient
   ground for knowledge; whatever I so perceive is true.


- Truth Rule :: Whenever I C&D perceive then what I perceive is true & I can be
                certain of it /as such/ 

- *Problem*: could a deceitful god make me go astray even when I have C&D ideas?
